(define (problem drone_problem_d1_r0_l15_p15_c15_g15_ct2)
(:domain p1)
(:objects
	drone1 - drone
	depot - location
	warehouse - location
	loc1 - location
	loc2 - location
	loc3 - location
	loc4 - location
	loc5 - location
	loc6 - location
	loc7 - location
	loc8 - location
	loc9 - location
	loc10 - location
	loc11 - location
	loc12 - location
	loc13 - location
	loc14 - location
	loc15 - location
	crate1 - crate
	crate2 - crate
	crate3 - crate
	crate4 - crate
	crate5 - crate
	crate6 - crate
	crate7 - crate
	crate8 - crate
	crate9 - crate
	crate10 - crate
	crate11 - crate
	crate12 - crate
	crate13 - crate
	crate14 - crate
	crate15 - crate
	food - content
	medicine - content
	person1 - person
	person2 - person
	person3 - person
	person4 - person
	person5 - person
	person6 - person
	person7 - person
	person8 - person
	person9 - person
	person10 - person
	person11 - person
	person12 - person
	person13 - person
	person14 - person
	person15 - person
	left right - arm
)
(:init
	(drone-at drone1 depot)
	(crate-at crate1 warehouse)
	(crate-at crate2 warehouse)
	(crate-at crate3 warehouse)
	(crate-at crate4 warehouse)
	(crate-at crate5 warehouse)
	(crate-at crate6 warehouse)
	(crate-at crate7 warehouse)
	(crate-at crate8 warehouse)
	(crate-at crate9 warehouse)
	(crate-at crate10 warehouse)
	(crate-at crate11 warehouse)
	(crate-at crate12 warehouse)
	(crate-at crate13 warehouse)
	(crate-at crate14 warehouse)
	(crate-at crate15 warehouse)
	(empty-arm drone1 left)
	(empty-arm drone1 right)
	(content-crate food crate1)
	(content-crate food crate2)
	(content-crate food crate3)
	(content-crate food crate4)
	(content-crate food crate5)
	(content-crate food crate6)
	(content-crate food crate7)
	(content-crate medicine crate8)
	(content-crate medicine crate9)
	(content-crate medicine crate10)
	(content-crate medicine crate11)
	(content-crate medicine crate12)
	(content-crate medicine crate13)
	(content-crate medicine crate14)
	(content-crate medicine crate15)
	(person-at person1 loc4)
	(person-at person2 loc11)
	(person-at person3 loc1)
	(person-at person4 loc3)
	(person-at person5 loc6)
	(person-at person6 loc2)
	(person-at person7 loc15)
	(person-at person8 loc11)
	(person-at person9 loc14)
	(person-at person10 loc13)
	(person-at person11 loc2)
	(person-at person12 loc8)
	(person-at person13 loc14)
	(person-at person14 loc11)
	(person-at person15 loc11)
	(person-need person1 medicine)
	(person-need person3 medicine)
	(person-need person4 food)
	(person-need person4 medicine)
	(person-need person5 food)
	(person-need person6 food)
	(person-need person6 medicine)
	(person-need person7 food)
	(person-need person7 medicine)
	(person-need person8 food)
	(person-need person11 medicine)
	(person-need person12 food)
	(person-need person13 medicine)
	(person-need person14 medicine)
	(person-need person15 food)
)
(:goal (and
	(drone-at drone1 depot)
	(has-content-person person1 medicine)
	(has-content-person person3 medicine)
	(has-content-person person4 food)
	(has-content-person person4 medicine)
	(has-content-person person5 food)
	(has-content-person person6 food)
	(has-content-person person6 medicine)
	(has-content-person person7 food)
	(has-content-person person7 medicine)
	(has-content-person person8 food)
	(has-content-person person11 medicine)
	(has-content-person person12 food)
	(has-content-person person13 medicine)
	(has-content-person person14 medicine)
	(has-content-person person15 food)
))
)
