(define (problem drone_problem_d1_r0_l30_p30_c30_g30_ct2)
(:domain p1)
(:objects
	drone1 - drone
	depot - location
	warehouse - location
	loc1 - location
	loc2 - location
	loc3 - location
	loc4 - location
	loc5 - location
	loc6 - location
	loc7 - location
	loc8 - location
	loc9 - location
	loc10 - location
	loc11 - location
	loc12 - location
	loc13 - location
	loc14 - location
	loc15 - location
	loc16 - location
	loc17 - location
	loc18 - location
	loc19 - location
	loc20 - location
	loc21 - location
	loc22 - location
	loc23 - location
	loc24 - location
	loc25 - location
	loc26 - location
	loc27 - location
	loc28 - location
	loc29 - location
	loc30 - location
	crate1 - crate
	crate2 - crate
	crate3 - crate
	crate4 - crate
	crate5 - crate
	crate6 - crate
	crate7 - crate
	crate8 - crate
	crate9 - crate
	crate10 - crate
	crate11 - crate
	crate12 - crate
	crate13 - crate
	crate14 - crate
	crate15 - crate
	crate16 - crate
	crate17 - crate
	crate18 - crate
	crate19 - crate
	crate20 - crate
	crate21 - crate
	crate22 - crate
	crate23 - crate
	crate24 - crate
	crate25 - crate
	crate26 - crate
	crate27 - crate
	crate28 - crate
	crate29 - crate
	crate30 - crate
	food - content
	medicine - content
	person1 - person
	person2 - person
	person3 - person
	person4 - person
	person5 - person
	person6 - person
	person7 - person
	person8 - person
	person9 - person
	person10 - person
	person11 - person
	person12 - person
	person13 - person
	person14 - person
	person15 - person
	person16 - person
	person17 - person
	person18 - person
	person19 - person
	person20 - person
	person21 - person
	person22 - person
	person23 - person
	person24 - person
	person25 - person
	person26 - person
	person27 - person
	person28 - person
	person29 - person
	person30 - person
	left right - arm
)
(:init
	(drone-at drone1 depot)
	(crate-at crate1 warehouse)
	(crate-at crate2 warehouse)
	(crate-at crate3 warehouse)
	(crate-at crate4 warehouse)
	(crate-at crate5 warehouse)
	(crate-at crate6 warehouse)
	(crate-at crate7 warehouse)
	(crate-at crate8 warehouse)
	(crate-at crate9 warehouse)
	(crate-at crate10 warehouse)
	(crate-at crate11 warehouse)
	(crate-at crate12 warehouse)
	(crate-at crate13 warehouse)
	(crate-at crate14 warehouse)
	(crate-at crate15 warehouse)
	(crate-at crate16 warehouse)
	(crate-at crate17 warehouse)
	(crate-at crate18 warehouse)
	(crate-at crate19 warehouse)
	(crate-at crate20 warehouse)
	(crate-at crate21 warehouse)
	(crate-at crate22 warehouse)
	(crate-at crate23 warehouse)
	(crate-at crate24 warehouse)
	(crate-at crate25 warehouse)
	(crate-at crate26 warehouse)
	(crate-at crate27 warehouse)
	(crate-at crate28 warehouse)
	(crate-at crate29 warehouse)
	(crate-at crate30 warehouse)
	(empty-arm drone1 left)
	(empty-arm drone1 right)
	(content-crate food crate1)
	(content-crate food crate2)
	(content-crate medicine crate3)
	(content-crate medicine crate4)
	(content-crate medicine crate5)
	(content-crate medicine crate6)
	(content-crate medicine crate7)
	(content-crate medicine crate8)
	(content-crate medicine crate9)
	(content-crate medicine crate10)
	(content-crate medicine crate11)
	(content-crate medicine crate12)
	(content-crate medicine crate13)
	(content-crate medicine crate14)
	(content-crate medicine crate15)
	(content-crate medicine crate16)
	(content-crate medicine crate17)
	(content-crate medicine crate18)
	(content-crate medicine crate19)
	(content-crate medicine crate20)
	(content-crate medicine crate21)
	(content-crate medicine crate22)
	(content-crate medicine crate23)
	(content-crate medicine crate24)
	(content-crate medicine crate25)
	(content-crate medicine crate26)
	(content-crate medicine crate27)
	(content-crate medicine crate28)
	(content-crate medicine crate29)
	(content-crate medicine crate30)
	(person-at person1 loc25)
	(person-at person2 loc27)
	(person-at person3 loc5)
	(person-at person4 loc22)
	(person-at person5 loc3)
	(person-at person6 loc29)
	(person-at person7 loc13)
	(person-at person8 loc19)
	(person-at person9 loc11)
	(person-at person10 loc19)
	(person-at person11 loc10)
	(person-at person12 loc17)
	(person-at person13 loc25)
	(person-at person14 loc16)
	(person-at person15 loc28)
	(person-at person16 loc15)
	(person-at person17 loc21)
	(person-at person18 loc17)
	(person-at person19 loc5)
	(person-at person20 loc19)
	(person-at person21 loc24)
	(person-at person22 loc18)
	(person-at person23 loc1)
	(person-at person24 loc27)
	(person-at person25 loc22)
	(person-at person26 loc25)
	(person-at person27 loc4)
	(person-at person28 loc18)
	(person-at person29 loc4)
	(person-at person30 loc18)
	(person-need person1 medicine)
	(person-need person2 medicine)
	(person-need person3 medicine)
	(person-need person4 medicine)
	(person-need person5 food)
	(person-need person5 medicine)
	(person-need person7 medicine)
	(person-need person8 medicine)
	(person-need person9 medicine)
	(person-need person10 medicine)
	(person-need person11 medicine)
	(person-need person12 medicine)
	(person-need person13 food)
	(person-need person13 medicine)
	(person-need person14 medicine)
	(person-need person15 medicine)
	(person-need person16 medicine)
	(person-need person17 medicine)
	(person-need person18 medicine)
	(person-need person19 medicine)
	(person-need person20 medicine)
	(person-need person21 medicine)
	(person-need person22 medicine)
	(person-need person23 medicine)
	(person-need person24 medicine)
	(person-need person25 medicine)
	(person-need person26 medicine)
	(person-need person27 medicine)
	(person-need person28 medicine)
	(person-need person30 medicine)
)
(:goal (and
	(drone-at drone1 depot)
	(has-content-person person1 medicine)
	(has-content-person person2 medicine)
	(has-content-person person3 medicine)
	(has-content-person person4 medicine)
	(has-content-person person5 food)
	(has-content-person person5 medicine)
	(has-content-person person7 medicine)
	(has-content-person person8 medicine)
	(has-content-person person9 medicine)
	(has-content-person person10 medicine)
	(has-content-person person11 medicine)
	(has-content-person person12 medicine)
	(has-content-person person13 food)
	(has-content-person person13 medicine)
	(has-content-person person14 medicine)
	(has-content-person person15 medicine)
	(has-content-person person16 medicine)
	(has-content-person person17 medicine)
	(has-content-person person18 medicine)
	(has-content-person person19 medicine)
	(has-content-person person20 medicine)
	(has-content-person person21 medicine)
	(has-content-person person22 medicine)
	(has-content-person person23 medicine)
	(has-content-person person24 medicine)
	(has-content-person person25 medicine)
	(has-content-person person26 medicine)
	(has-content-person person27 medicine)
	(has-content-person person28 medicine)
	(has-content-person person30 medicine)
))
)
