(define (problem drone_problem_d1_r0_l41_p41_c41_g41_ct2)
(:domain p1)
(:objects
	drone1 - drone
	depot - location
	loc1 - location
	loc2 - location
	loc3 - location
	loc4 - location
	loc5 - location
	loc6 - location
	loc7 - location
	loc8 - location
	loc9 - location
	loc10 - location
	loc11 - location
	loc12 - location
	loc13 - location
	loc14 - location
	loc15 - location
	loc16 - location
	loc17 - location
	loc18 - location
	loc19 - location
	loc20 - location
	loc21 - location
	loc22 - location
	loc23 - location
	loc24 - location
	loc25 - location
	loc26 - location
	loc27 - location
	loc28 - location
	loc29 - location
	loc30 - location
	loc31 - location
	loc32 - location
	loc33 - location
	loc34 - location
	loc35 - location
	loc36 - location
	loc37 - location
	loc38 - location
	loc39 - location
	loc40 - location
	loc41 - location
	crate1 - crate
	crate2 - crate
	crate3 - crate
	crate4 - crate
	crate5 - crate
	crate6 - crate
	crate7 - crate
	crate8 - crate
	crate9 - crate
	crate10 - crate
	crate11 - crate
	crate12 - crate
	crate13 - crate
	crate14 - crate
	crate15 - crate
	crate16 - crate
	crate17 - crate
	crate18 - crate
	crate19 - crate
	crate20 - crate
	crate21 - crate
	crate22 - crate
	crate23 - crate
	crate24 - crate
	crate25 - crate
	crate26 - crate
	crate27 - crate
	crate28 - crate
	crate29 - crate
	crate30 - crate
	crate31 - crate
	crate32 - crate
	crate33 - crate
	crate34 - crate
	crate35 - crate
	crate36 - crate
	crate37 - crate
	crate38 - crate
	crate39 - crate
	crate40 - crate
	crate41 - crate
	food - content
	medicine - content
	person1 - person
	person2 - person
	person3 - person
	person4 - person
	person5 - person
	person6 - person
	person7 - person
	person8 - person
	person9 - person
	person10 - person
	person11 - person
	person12 - person
	person13 - person
	person14 - person
	person15 - person
	person16 - person
	person17 - person
	person18 - person
	person19 - person
	person20 - person
	person21 - person
	person22 - person
	person23 - person
	person24 - person
	person25 - person
	person26 - person
	person27 - person
	person28 - person
	person29 - person
	person30 - person
	person31 - person
	person32 - person
	person33 - person
	person34 - person
	person35 - person
	person36 - person
	person37 - person
	person38 - person
	person39 - person
	person40 - person
	person41 - person
	left right - arm
)
(:init
	(drone-at drone1 depot)
	(crate-at crate1 depot)
	(crate-at crate2 depot)
	(crate-at crate3 depot)
	(crate-at crate4 depot)
	(crate-at crate5 depot)
	(crate-at crate6 depot)
	(crate-at crate7 depot)
	(crate-at crate8 depot)
	(crate-at crate9 depot)
	(crate-at crate10 depot)
	(crate-at crate11 depot)
	(crate-at crate12 depot)
	(crate-at crate13 depot)
	(crate-at crate14 depot)
	(crate-at crate15 depot)
	(crate-at crate16 depot)
	(crate-at crate17 depot)
	(crate-at crate18 depot)
	(crate-at crate19 depot)
	(crate-at crate20 depot)
	(crate-at crate21 depot)
	(crate-at crate22 depot)
	(crate-at crate23 depot)
	(crate-at crate24 depot)
	(crate-at crate25 depot)
	(crate-at crate26 depot)
	(crate-at crate27 depot)
	(crate-at crate28 depot)
	(crate-at crate29 depot)
	(crate-at crate30 depot)
	(crate-at crate31 depot)
	(crate-at crate32 depot)
	(crate-at crate33 depot)
	(crate-at crate34 depot)
	(crate-at crate35 depot)
	(crate-at crate36 depot)
	(crate-at crate37 depot)
	(crate-at crate38 depot)
	(crate-at crate39 depot)
	(crate-at crate40 depot)
	(crate-at crate41 depot)
	(empty-arm left)
	(empty-arm right)
	(content-crate food crate1)
	(content-crate food crate2)
	(content-crate food crate3)
	(content-crate food crate4)
	(content-crate food crate5)
	(content-crate food crate6)
	(content-crate food crate7)
	(content-crate food crate8)
	(content-crate food crate9)
	(content-crate food crate10)
	(content-crate food crate11)
	(content-crate food crate12)
	(content-crate food crate13)
	(content-crate food crate14)
	(content-crate food crate15)
	(content-crate food crate16)
	(content-crate food crate17)
	(content-crate food crate18)
	(content-crate food crate19)
	(content-crate food crate20)
	(content-crate food crate21)
	(content-crate food crate22)
	(content-crate food crate23)
	(content-crate medicine crate24)
	(content-crate medicine crate25)
	(content-crate medicine crate26)
	(content-crate medicine crate27)
	(content-crate medicine crate28)
	(content-crate medicine crate29)
	(content-crate medicine crate30)
	(content-crate medicine crate31)
	(content-crate medicine crate32)
	(content-crate medicine crate33)
	(content-crate medicine crate34)
	(content-crate medicine crate35)
	(content-crate medicine crate36)
	(content-crate medicine crate37)
	(content-crate medicine crate38)
	(content-crate medicine crate39)
	(content-crate medicine crate40)
	(content-crate medicine crate41)
	(person-at person1 loc20)
	(person-at person2 loc20)
	(person-at person3 loc3)
	(person-at person4 loc31)
	(person-at person5 loc30)
	(person-at person6 loc9)
	(person-at person7 loc26)
	(person-at person8 loc16)
	(person-at person9 loc37)
	(person-at person10 loc24)
	(person-at person11 loc16)
	(person-at person12 loc18)
	(person-at person13 loc5)
	(person-at person14 loc8)
	(person-at person15 loc19)
	(person-at person16 loc31)
	(person-at person17 loc18)
	(person-at person18 loc7)
	(person-at person19 loc39)
	(person-at person20 loc3)
	(person-at person21 loc31)
	(person-at person22 loc39)
	(person-at person23 loc35)
	(person-at person24 loc17)
	(person-at person25 loc33)
	(person-at person26 loc4)
	(person-at person27 loc2)
	(person-at person28 loc37)
	(person-at person29 loc37)
	(person-at person30 loc21)
	(person-at person31 loc12)
	(person-at person32 loc12)
	(person-at person33 loc41)
	(person-at person34 loc38)
	(person-at person35 loc37)
	(person-at person36 loc1)
	(person-at person37 loc36)
	(person-at person38 loc15)
	(person-at person39 loc35)
	(person-at person40 loc6)
	(person-at person41 loc18)
	(person-need person2 food)
	(person-need person2 medicine)
	(person-need person3 medicine)
	(person-need person4 food)
	(person-need person5 medicine)
	(person-need person7 food)
	(person-need person7 medicine)
	(person-need person8 food)
	(person-need person9 food)
	(person-need person11 medicine)
	(person-need person12 medicine)
	(person-need person13 medicine)
	(person-need person14 food)
	(person-need person17 food)
	(person-need person18 food)
	(person-need person18 medicine)
	(person-need person19 food)
	(person-need person19 medicine)
	(person-need person20 medicine)
	(person-need person22 food)
	(person-need person23 food)
	(person-need person24 food)
	(person-need person24 medicine)
	(person-need person25 food)
	(person-need person25 medicine)
	(person-need person26 food)
	(person-need person29 food)
	(person-need person29 medicine)
	(person-need person30 food)
	(person-need person31 food)
	(person-need person32 food)
	(person-need person32 medicine)
	(person-need person33 food)
	(person-need person33 medicine)
	(person-need person35 food)
	(person-need person35 medicine)
	(person-need person36 food)
	(person-need person36 medicine)
	(person-need person38 food)
	(person-need person39 medicine)
	(person-need person40 food)
)
(:goal (and
	(drone-at drone1 depot)
	(has-content-person person2 food)
	(has-content-person person2 medicine)
	(has-content-person person3 medicine)
	(has-content-person person4 food)
	(has-content-person person5 medicine)
	(has-content-person person7 food)
	(has-content-person person7 medicine)
	(has-content-person person8 food)
	(has-content-person person9 food)
	(has-content-person person11 medicine)
	(has-content-person person12 medicine)
	(has-content-person person13 medicine)
	(has-content-person person14 food)
	(has-content-person person17 food)
	(has-content-person person18 food)
	(has-content-person person18 medicine)
	(has-content-person person19 food)
	(has-content-person person19 medicine)
	(has-content-person person20 medicine)
	(has-content-person person22 food)
	(has-content-person person23 food)
	(has-content-person person24 food)
	(has-content-person person24 medicine)
	(has-content-person person25 food)
	(has-content-person person25 medicine)
	(has-content-person person26 food)
	(has-content-person person29 food)
	(has-content-person person29 medicine)
	(has-content-person person30 food)
	(has-content-person person31 food)
	(has-content-person person32 food)
	(has-content-person person32 medicine)
	(has-content-person person33 food)
	(has-content-person person33 medicine)
	(has-content-person person35 food)
	(has-content-person person35 medicine)
	(has-content-person person36 food)
	(has-content-person person36 medicine)
	(has-content-person person38 food)
	(has-content-person person39 medicine)
	(has-content-person person40 food)
))
)
