(define (problem drone_problem_d1_r0_l33_p33_c33_g33_ct2)
(:domain p1)
(:objects
	drone1 - drone
	depot - location
	warehouse - location
	loc1 - location
	loc2 - location
	loc3 - location
	loc4 - location
	loc5 - location
	loc6 - location
	loc7 - location
	loc8 - location
	loc9 - location
	loc10 - location
	loc11 - location
	loc12 - location
	loc13 - location
	loc14 - location
	loc15 - location
	loc16 - location
	loc17 - location
	loc18 - location
	loc19 - location
	loc20 - location
	loc21 - location
	loc22 - location
	loc23 - location
	loc24 - location
	loc25 - location
	loc26 - location
	loc27 - location
	loc28 - location
	loc29 - location
	loc30 - location
	loc31 - location
	loc32 - location
	loc33 - location
	crate1 - crate
	crate2 - crate
	crate3 - crate
	crate4 - crate
	crate5 - crate
	crate6 - crate
	crate7 - crate
	crate8 - crate
	crate9 - crate
	crate10 - crate
	crate11 - crate
	crate12 - crate
	crate13 - crate
	crate14 - crate
	crate15 - crate
	crate16 - crate
	crate17 - crate
	crate18 - crate
	crate19 - crate
	crate20 - crate
	crate21 - crate
	crate22 - crate
	crate23 - crate
	crate24 - crate
	crate25 - crate
	crate26 - crate
	crate27 - crate
	crate28 - crate
	crate29 - crate
	crate30 - crate
	crate31 - crate
	crate32 - crate
	crate33 - crate
	food - content
	medicine - content
	person1 - person
	person2 - person
	person3 - person
	person4 - person
	person5 - person
	person6 - person
	person7 - person
	person8 - person
	person9 - person
	person10 - person
	person11 - person
	person12 - person
	person13 - person
	person14 - person
	person15 - person
	person16 - person
	person17 - person
	person18 - person
	person19 - person
	person20 - person
	person21 - person
	person22 - person
	person23 - person
	person24 - person
	person25 - person
	person26 - person
	person27 - person
	person28 - person
	person29 - person
	person30 - person
	person31 - person
	person32 - person
	person33 - person
	left right - arm
)
(:init
	(drone-at drone1 depot)
	(crate-at crate1 warehouse)
	(crate-at crate2 warehouse)
	(crate-at crate3 warehouse)
	(crate-at crate4 warehouse)
	(crate-at crate5 warehouse)
	(crate-at crate6 warehouse)
	(crate-at crate7 warehouse)
	(crate-at crate8 warehouse)
	(crate-at crate9 warehouse)
	(crate-at crate10 warehouse)
	(crate-at crate11 warehouse)
	(crate-at crate12 warehouse)
	(crate-at crate13 warehouse)
	(crate-at crate14 warehouse)
	(crate-at crate15 warehouse)
	(crate-at crate16 warehouse)
	(crate-at crate17 warehouse)
	(crate-at crate18 warehouse)
	(crate-at crate19 warehouse)
	(crate-at crate20 warehouse)
	(crate-at crate21 warehouse)
	(crate-at crate22 warehouse)
	(crate-at crate23 warehouse)
	(crate-at crate24 warehouse)
	(crate-at crate25 warehouse)
	(crate-at crate26 warehouse)
	(crate-at crate27 warehouse)
	(crate-at crate28 warehouse)
	(crate-at crate29 warehouse)
	(crate-at crate30 warehouse)
	(crate-at crate31 warehouse)
	(crate-at crate32 warehouse)
	(crate-at crate33 warehouse)
	(empty-arm drone1 left)
	(empty-arm drone1 right)
	(content-crate food crate1)
	(content-crate food crate2)
	(content-crate food crate3)
	(content-crate food crate4)
	(content-crate food crate5)
	(content-crate food crate6)
	(content-crate food crate7)
	(content-crate food crate8)
	(content-crate food crate9)
	(content-crate food crate10)
	(content-crate food crate11)
	(content-crate food crate12)
	(content-crate food crate13)
	(content-crate food crate14)
	(content-crate food crate15)
	(content-crate food crate16)
	(content-crate food crate17)
	(content-crate food crate18)
	(content-crate food crate19)
	(content-crate food crate20)
	(content-crate food crate21)
	(content-crate food crate22)
	(content-crate food crate23)
	(content-crate food crate24)
	(content-crate medicine crate25)
	(content-crate medicine crate26)
	(content-crate medicine crate27)
	(content-crate medicine crate28)
	(content-crate medicine crate29)
	(content-crate medicine crate30)
	(content-crate medicine crate31)
	(content-crate medicine crate32)
	(content-crate medicine crate33)
	(person-at person1 loc16)
	(person-at person2 loc6)
	(person-at person3 loc32)
	(person-at person4 loc2)
	(person-at person5 loc3)
	(person-at person6 loc23)
	(person-at person7 loc25)
	(person-at person8 loc25)
	(person-at person9 loc10)
	(person-at person10 loc17)
	(person-at person11 loc4)
	(person-at person12 loc11)
	(person-at person13 loc22)
	(person-at person14 loc7)
	(person-at person15 loc20)
	(person-at person16 loc25)
	(person-at person17 loc31)
	(person-at person18 loc12)
	(person-at person19 loc23)
	(person-at person20 loc21)
	(person-at person21 loc25)
	(person-at person22 loc15)
	(person-at person23 loc3)
	(person-at person24 loc6)
	(person-at person25 loc10)
	(person-at person26 loc8)
	(person-at person27 loc16)
	(person-at person28 loc2)
	(person-at person29 loc20)
	(person-at person30 loc1)
	(person-at person31 loc33)
	(person-at person32 loc30)
	(person-at person33 loc13)
	(person-need person1 food)
	(person-need person2 food)
	(person-need person2 medicine)
	(person-need person3 food)
	(person-need person3 medicine)
	(person-need person4 food)
	(person-need person5 food)
	(person-need person5 medicine)
	(person-need person6 food)
	(person-need person7 food)
	(person-need person7 medicine)
	(person-need person8 food)
	(person-need person9 food)
	(person-need person9 medicine)
	(person-need person10 food)
	(person-need person12 food)
	(person-need person14 medicine)
	(person-need person15 food)
	(person-need person16 food)
	(person-need person16 medicine)
	(person-need person17 food)
	(person-need person18 food)
	(person-need person20 food)
	(person-need person21 medicine)
	(person-need person22 food)
	(person-need person23 food)
	(person-need person25 food)
	(person-need person26 food)
	(person-need person27 food)
	(person-need person28 food)
	(person-need person29 food)
	(person-need person30 food)
	(person-need person30 medicine)
)
(:goal (and
	(drone-at drone1 depot)
	(has-content-person person1 food)
	(has-content-person person2 food)
	(has-content-person person2 medicine)
	(has-content-person person3 food)
	(has-content-person person3 medicine)
	(has-content-person person4 food)
	(has-content-person person5 food)
	(has-content-person person5 medicine)
	(has-content-person person6 food)
	(has-content-person person7 food)
	(has-content-person person7 medicine)
	(has-content-person person8 food)
	(has-content-person person9 food)
	(has-content-person person9 medicine)
	(has-content-person person10 food)
	(has-content-person person12 food)
	(has-content-person person14 medicine)
	(has-content-person person15 food)
	(has-content-person person16 food)
	(has-content-person person16 medicine)
	(has-content-person person17 food)
	(has-content-person person18 food)
	(has-content-person person20 food)
	(has-content-person person21 medicine)
	(has-content-person person22 food)
	(has-content-person person23 food)
	(has-content-person person25 food)
	(has-content-person person26 food)
	(has-content-person person27 food)
	(has-content-person person28 food)
	(has-content-person person29 food)
	(has-content-person person30 food)
	(has-content-person person30 medicine)
))
)
