(define (problem drone_problem_d1_r0_l60_p60_c60_g60_ct2)
(:domain p1)
(:objects
	drone1 - drone
	depot - location
	warehouse - location
	loc1 - location
	loc2 - location
	loc3 - location
	loc4 - location
	loc5 - location
	loc6 - location
	loc7 - location
	loc8 - location
	loc9 - location
	loc10 - location
	loc11 - location
	loc12 - location
	loc13 - location
	loc14 - location
	loc15 - location
	loc16 - location
	loc17 - location
	loc18 - location
	loc19 - location
	loc20 - location
	loc21 - location
	loc22 - location
	loc23 - location
	loc24 - location
	loc25 - location
	loc26 - location
	loc27 - location
	loc28 - location
	loc29 - location
	loc30 - location
	loc31 - location
	loc32 - location
	loc33 - location
	loc34 - location
	loc35 - location
	loc36 - location
	loc37 - location
	loc38 - location
	loc39 - location
	loc40 - location
	loc41 - location
	loc42 - location
	loc43 - location
	loc44 - location
	loc45 - location
	loc46 - location
	loc47 - location
	loc48 - location
	loc49 - location
	loc50 - location
	loc51 - location
	loc52 - location
	loc53 - location
	loc54 - location
	loc55 - location
	loc56 - location
	loc57 - location
	loc58 - location
	loc59 - location
	loc60 - location
	crate1 - crate
	crate2 - crate
	crate3 - crate
	crate4 - crate
	crate5 - crate
	crate6 - crate
	crate7 - crate
	crate8 - crate
	crate9 - crate
	crate10 - crate
	crate11 - crate
	crate12 - crate
	crate13 - crate
	crate14 - crate
	crate15 - crate
	crate16 - crate
	crate17 - crate
	crate18 - crate
	crate19 - crate
	crate20 - crate
	crate21 - crate
	crate22 - crate
	crate23 - crate
	crate24 - crate
	crate25 - crate
	crate26 - crate
	crate27 - crate
	crate28 - crate
	crate29 - crate
	crate30 - crate
	crate31 - crate
	crate32 - crate
	crate33 - crate
	crate34 - crate
	crate35 - crate
	crate36 - crate
	crate37 - crate
	crate38 - crate
	crate39 - crate
	crate40 - crate
	crate41 - crate
	crate42 - crate
	crate43 - crate
	crate44 - crate
	crate45 - crate
	crate46 - crate
	crate47 - crate
	crate48 - crate
	crate49 - crate
	crate50 - crate
	crate51 - crate
	crate52 - crate
	crate53 - crate
	crate54 - crate
	crate55 - crate
	crate56 - crate
	crate57 - crate
	crate58 - crate
	crate59 - crate
	crate60 - crate
	food - content
	medicine - content
	person1 - person
	person2 - person
	person3 - person
	person4 - person
	person5 - person
	person6 - person
	person7 - person
	person8 - person
	person9 - person
	person10 - person
	person11 - person
	person12 - person
	person13 - person
	person14 - person
	person15 - person
	person16 - person
	person17 - person
	person18 - person
	person19 - person
	person20 - person
	person21 - person
	person22 - person
	person23 - person
	person24 - person
	person25 - person
	person26 - person
	person27 - person
	person28 - person
	person29 - person
	person30 - person
	person31 - person
	person32 - person
	person33 - person
	person34 - person
	person35 - person
	person36 - person
	person37 - person
	person38 - person
	person39 - person
	person40 - person
	person41 - person
	person42 - person
	person43 - person
	person44 - person
	person45 - person
	person46 - person
	person47 - person
	person48 - person
	person49 - person
	person50 - person
	person51 - person
	person52 - person
	person53 - person
	person54 - person
	person55 - person
	person56 - person
	person57 - person
	person58 - person
	person59 - person
	person60 - person
	left right - arm
)
(:init
	(drone-at drone1 depot)
	(crate-at crate1 warehouse)
	(crate-at crate2 warehouse)
	(crate-at crate3 warehouse)
	(crate-at crate4 warehouse)
	(crate-at crate5 warehouse)
	(crate-at crate6 warehouse)
	(crate-at crate7 warehouse)
	(crate-at crate8 warehouse)
	(crate-at crate9 warehouse)
	(crate-at crate10 warehouse)
	(crate-at crate11 warehouse)
	(crate-at crate12 warehouse)
	(crate-at crate13 warehouse)
	(crate-at crate14 warehouse)
	(crate-at crate15 warehouse)
	(crate-at crate16 warehouse)
	(crate-at crate17 warehouse)
	(crate-at crate18 warehouse)
	(crate-at crate19 warehouse)
	(crate-at crate20 warehouse)
	(crate-at crate21 warehouse)
	(crate-at crate22 warehouse)
	(crate-at crate23 warehouse)
	(crate-at crate24 warehouse)
	(crate-at crate25 warehouse)
	(crate-at crate26 warehouse)
	(crate-at crate27 warehouse)
	(crate-at crate28 warehouse)
	(crate-at crate29 warehouse)
	(crate-at crate30 warehouse)
	(crate-at crate31 warehouse)
	(crate-at crate32 warehouse)
	(crate-at crate33 warehouse)
	(crate-at crate34 warehouse)
	(crate-at crate35 warehouse)
	(crate-at crate36 warehouse)
	(crate-at crate37 warehouse)
	(crate-at crate38 warehouse)
	(crate-at crate39 warehouse)
	(crate-at crate40 warehouse)
	(crate-at crate41 warehouse)
	(crate-at crate42 warehouse)
	(crate-at crate43 warehouse)
	(crate-at crate44 warehouse)
	(crate-at crate45 warehouse)
	(crate-at crate46 warehouse)
	(crate-at crate47 warehouse)
	(crate-at crate48 warehouse)
	(crate-at crate49 warehouse)
	(crate-at crate50 warehouse)
	(crate-at crate51 warehouse)
	(crate-at crate52 warehouse)
	(crate-at crate53 warehouse)
	(crate-at crate54 warehouse)
	(crate-at crate55 warehouse)
	(crate-at crate56 warehouse)
	(crate-at crate57 warehouse)
	(crate-at crate58 warehouse)
	(crate-at crate59 warehouse)
	(crate-at crate60 warehouse)
	(empty-arm drone1 left)
	(empty-arm drone1 right)
	(content-crate food crate1)
	(content-crate food crate2)
	(content-crate food crate3)
	(content-crate food crate4)
	(content-crate food crate5)
	(content-crate food crate6)
	(content-crate food crate7)
	(content-crate food crate8)
	(content-crate food crate9)
	(content-crate food crate10)
	(content-crate food crate11)
	(content-crate food crate12)
	(content-crate food crate13)
	(content-crate food crate14)
	(content-crate food crate15)
	(content-crate food crate16)
	(content-crate food crate17)
	(content-crate food crate18)
	(content-crate food crate19)
	(content-crate food crate20)
	(content-crate food crate21)
	(content-crate food crate22)
	(content-crate food crate23)
	(content-crate food crate24)
	(content-crate food crate25)
	(content-crate food crate26)
	(content-crate food crate27)
	(content-crate food crate28)
	(content-crate food crate29)
	(content-crate food crate30)
	(content-crate food crate31)
	(content-crate food crate32)
	(content-crate food crate33)
	(content-crate food crate34)
	(content-crate food crate35)
	(content-crate food crate36)
	(content-crate food crate37)
	(content-crate food crate38)
	(content-crate food crate39)
	(content-crate food crate40)
	(content-crate food crate41)
	(content-crate food crate42)
	(content-crate medicine crate43)
	(content-crate medicine crate44)
	(content-crate medicine crate45)
	(content-crate medicine crate46)
	(content-crate medicine crate47)
	(content-crate medicine crate48)
	(content-crate medicine crate49)
	(content-crate medicine crate50)
	(content-crate medicine crate51)
	(content-crate medicine crate52)
	(content-crate medicine crate53)
	(content-crate medicine crate54)
	(content-crate medicine crate55)
	(content-crate medicine crate56)
	(content-crate medicine crate57)
	(content-crate medicine crate58)
	(content-crate medicine crate59)
	(content-crate medicine crate60)
	(person-at person1 loc33)
	(person-at person2 loc8)
	(person-at person3 loc13)
	(person-at person4 loc13)
	(person-at person5 loc2)
	(person-at person6 loc17)
	(person-at person7 loc13)
	(person-at person8 loc23)
	(person-at person9 loc13)
	(person-at person10 loc36)
	(person-at person11 loc17)
	(person-at person12 loc43)
	(person-at person13 loc48)
	(person-at person14 loc26)
	(person-at person15 loc15)
	(person-at person16 loc44)
	(person-at person17 loc59)
	(person-at person18 loc11)
	(person-at person19 loc34)
	(person-at person20 loc15)
	(person-at person21 loc53)
	(person-at person22 loc35)
	(person-at person23 loc52)
	(person-at person24 loc53)
	(person-at person25 loc10)
	(person-at person26 loc6)
	(person-at person27 loc7)
	(person-at person28 loc49)
	(person-at person29 loc39)
	(person-at person30 loc25)
	(person-at person31 loc25)
	(person-at person32 loc13)
	(person-at person33 loc40)
	(person-at person34 loc13)
	(person-at person35 loc25)
	(person-at person36 loc37)
	(person-at person37 loc37)
	(person-at person38 loc52)
	(person-at person39 loc26)
	(person-at person40 loc23)
	(person-at person41 loc14)
	(person-at person42 loc25)
	(person-at person43 loc32)
	(person-at person44 loc34)
	(person-at person45 loc49)
	(person-at person46 loc7)
	(person-at person47 loc5)
	(person-at person48 loc27)
	(person-at person49 loc37)
	(person-at person50 loc38)
	(person-at person51 loc21)
	(person-at person52 loc25)
	(person-at person53 loc27)
	(person-at person54 loc35)
	(person-at person55 loc38)
	(person-at person56 loc43)
	(person-at person57 loc52)
	(person-at person58 loc36)
	(person-at person59 loc58)
	(person-at person60 loc51)
	(person-need person1 food)
	(person-need person2 food)
	(person-need person4 food)
	(person-need person4 medicine)
	(person-need person6 food)
	(person-need person8 food)
	(person-need person8 medicine)
	(person-need person9 medicine)
	(person-need person10 food)
	(person-need person11 medicine)
	(person-need person12 food)
	(person-need person12 medicine)
	(person-need person13 food)
	(person-need person15 food)
	(person-need person16 food)
	(person-need person16 medicine)
	(person-need person17 food)
	(person-need person18 food)
	(person-need person19 food)
	(person-need person19 medicine)
	(person-need person20 food)
	(person-need person21 food)
	(person-need person22 food)
	(person-need person22 medicine)
	(person-need person24 food)
	(person-need person25 food)
	(person-need person27 food)
	(person-need person28 food)
	(person-need person28 medicine)
	(person-need person29 food)
	(person-need person30 food)
	(person-need person31 food)
	(person-need person33 food)
	(person-need person33 medicine)
	(person-need person34 food)
	(person-need person37 food)
	(person-need person38 food)
	(person-need person38 medicine)
	(person-need person40 food)
	(person-need person40 medicine)
	(person-need person41 food)
	(person-need person42 food)
	(person-need person43 medicine)
	(person-need person44 food)
	(person-need person45 food)
	(person-need person46 medicine)
	(person-need person48 food)
	(person-need person49 food)
	(person-need person50 food)
	(person-need person51 food)
	(person-need person51 medicine)
	(person-need person52 food)
	(person-need person54 food)
	(person-need person55 food)
	(person-need person55 medicine)
	(person-need person56 medicine)
	(person-need person57 food)
	(person-need person58 food)
	(person-need person59 food)
	(person-need person60 medicine)
)
(:goal (and
	(drone-at drone1 depot)
	(has-content-person person1 food)
	(has-content-person person2 food)
	(has-content-person person4 food)
	(has-content-person person4 medicine)
	(has-content-person person6 food)
	(has-content-person person8 food)
	(has-content-person person8 medicine)
	(has-content-person person9 medicine)
	(has-content-person person10 food)
	(has-content-person person11 medicine)
	(has-content-person person12 food)
	(has-content-person person12 medicine)
	(has-content-person person13 food)
	(has-content-person person15 food)
	(has-content-person person16 food)
	(has-content-person person16 medicine)
	(has-content-person person17 food)
	(has-content-person person18 food)
	(has-content-person person19 food)
	(has-content-person person19 medicine)
	(has-content-person person20 food)
	(has-content-person person21 food)
	(has-content-person person22 food)
	(has-content-person person22 medicine)
	(has-content-person person24 food)
	(has-content-person person25 food)
	(has-content-person person27 food)
	(has-content-person person28 food)
	(has-content-person person28 medicine)
	(has-content-person person29 food)
	(has-content-person person30 food)
	(has-content-person person31 food)
	(has-content-person person33 food)
	(has-content-person person33 medicine)
	(has-content-person person34 food)
	(has-content-person person37 food)
	(has-content-person person38 food)
	(has-content-person person38 medicine)
	(has-content-person person40 food)
	(has-content-person person40 medicine)
	(has-content-person person41 food)
	(has-content-person person42 food)
	(has-content-person person43 medicine)
	(has-content-person person44 food)
	(has-content-person person45 food)
	(has-content-person person46 medicine)
	(has-content-person person48 food)
	(has-content-person person49 food)
	(has-content-person person50 food)
	(has-content-person person51 food)
	(has-content-person person51 medicine)
	(has-content-person person52 food)
	(has-content-person person54 food)
	(has-content-person person55 food)
	(has-content-person person55 medicine)
	(has-content-person person56 medicine)
	(has-content-person person57 food)
	(has-content-person person58 food)
	(has-content-person person59 food)
	(has-content-person person60 medicine)
))
)
