(define (problem drone_problem_d1_r0_l87_p87_c87_g87_ct2)
(:domain p1)
(:objects
	drone1 - drone
	depot - location
	warehouse - location
	loc1 - location
	loc2 - location
	loc3 - location
	loc4 - location
	loc5 - location
	loc6 - location
	loc7 - location
	loc8 - location
	loc9 - location
	loc10 - location
	loc11 - location
	loc12 - location
	loc13 - location
	loc14 - location
	loc15 - location
	loc16 - location
	loc17 - location
	loc18 - location
	loc19 - location
	loc20 - location
	loc21 - location
	loc22 - location
	loc23 - location
	loc24 - location
	loc25 - location
	loc26 - location
	loc27 - location
	loc28 - location
	loc29 - location
	loc30 - location
	loc31 - location
	loc32 - location
	loc33 - location
	loc34 - location
	loc35 - location
	loc36 - location
	loc37 - location
	loc38 - location
	loc39 - location
	loc40 - location
	loc41 - location
	loc42 - location
	loc43 - location
	loc44 - location
	loc45 - location
	loc46 - location
	loc47 - location
	loc48 - location
	loc49 - location
	loc50 - location
	loc51 - location
	loc52 - location
	loc53 - location
	loc54 - location
	loc55 - location
	loc56 - location
	loc57 - location
	loc58 - location
	loc59 - location
	loc60 - location
	loc61 - location
	loc62 - location
	loc63 - location
	loc64 - location
	loc65 - location
	loc66 - location
	loc67 - location
	loc68 - location
	loc69 - location
	loc70 - location
	loc71 - location
	loc72 - location
	loc73 - location
	loc74 - location
	loc75 - location
	loc76 - location
	loc77 - location
	loc78 - location
	loc79 - location
	loc80 - location
	loc81 - location
	loc82 - location
	loc83 - location
	loc84 - location
	loc85 - location
	loc86 - location
	loc87 - location
	crate1 - crate
	crate2 - crate
	crate3 - crate
	crate4 - crate
	crate5 - crate
	crate6 - crate
	crate7 - crate
	crate8 - crate
	crate9 - crate
	crate10 - crate
	crate11 - crate
	crate12 - crate
	crate13 - crate
	crate14 - crate
	crate15 - crate
	crate16 - crate
	crate17 - crate
	crate18 - crate
	crate19 - crate
	crate20 - crate
	crate21 - crate
	crate22 - crate
	crate23 - crate
	crate24 - crate
	crate25 - crate
	crate26 - crate
	crate27 - crate
	crate28 - crate
	crate29 - crate
	crate30 - crate
	crate31 - crate
	crate32 - crate
	crate33 - crate
	crate34 - crate
	crate35 - crate
	crate36 - crate
	crate37 - crate
	crate38 - crate
	crate39 - crate
	crate40 - crate
	crate41 - crate
	crate42 - crate
	crate43 - crate
	crate44 - crate
	crate45 - crate
	crate46 - crate
	crate47 - crate
	crate48 - crate
	crate49 - crate
	crate50 - crate
	crate51 - crate
	crate52 - crate
	crate53 - crate
	crate54 - crate
	crate55 - crate
	crate56 - crate
	crate57 - crate
	crate58 - crate
	crate59 - crate
	crate60 - crate
	crate61 - crate
	crate62 - crate
	crate63 - crate
	crate64 - crate
	crate65 - crate
	crate66 - crate
	crate67 - crate
	crate68 - crate
	crate69 - crate
	crate70 - crate
	crate71 - crate
	crate72 - crate
	crate73 - crate
	crate74 - crate
	crate75 - crate
	crate76 - crate
	crate77 - crate
	crate78 - crate
	crate79 - crate
	crate80 - crate
	crate81 - crate
	crate82 - crate
	crate83 - crate
	crate84 - crate
	crate85 - crate
	crate86 - crate
	crate87 - crate
	food - content
	medicine - content
	person1 - person
	person2 - person
	person3 - person
	person4 - person
	person5 - person
	person6 - person
	person7 - person
	person8 - person
	person9 - person
	person10 - person
	person11 - person
	person12 - person
	person13 - person
	person14 - person
	person15 - person
	person16 - person
	person17 - person
	person18 - person
	person19 - person
	person20 - person
	person21 - person
	person22 - person
	person23 - person
	person24 - person
	person25 - person
	person26 - person
	person27 - person
	person28 - person
	person29 - person
	person30 - person
	person31 - person
	person32 - person
	person33 - person
	person34 - person
	person35 - person
	person36 - person
	person37 - person
	person38 - person
	person39 - person
	person40 - person
	person41 - person
	person42 - person
	person43 - person
	person44 - person
	person45 - person
	person46 - person
	person47 - person
	person48 - person
	person49 - person
	person50 - person
	person51 - person
	person52 - person
	person53 - person
	person54 - person
	person55 - person
	person56 - person
	person57 - person
	person58 - person
	person59 - person
	person60 - person
	person61 - person
	person62 - person
	person63 - person
	person64 - person
	person65 - person
	person66 - person
	person67 - person
	person68 - person
	person69 - person
	person70 - person
	person71 - person
	person72 - person
	person73 - person
	person74 - person
	person75 - person
	person76 - person
	person77 - person
	person78 - person
	person79 - person
	person80 - person
	person81 - person
	person82 - person
	person83 - person
	person84 - person
	person85 - person
	person86 - person
	person87 - person
	left right - arm
)
(:init
	(drone-at drone1 depot)
	(crate-at crate1 warehouse)
	(crate-at crate2 warehouse)
	(crate-at crate3 warehouse)
	(crate-at crate4 warehouse)
	(crate-at crate5 warehouse)
	(crate-at crate6 warehouse)
	(crate-at crate7 warehouse)
	(crate-at crate8 warehouse)
	(crate-at crate9 warehouse)
	(crate-at crate10 warehouse)
	(crate-at crate11 warehouse)
	(crate-at crate12 warehouse)
	(crate-at crate13 warehouse)
	(crate-at crate14 warehouse)
	(crate-at crate15 warehouse)
	(crate-at crate16 warehouse)
	(crate-at crate17 warehouse)
	(crate-at crate18 warehouse)
	(crate-at crate19 warehouse)
	(crate-at crate20 warehouse)
	(crate-at crate21 warehouse)
	(crate-at crate22 warehouse)
	(crate-at crate23 warehouse)
	(crate-at crate24 warehouse)
	(crate-at crate25 warehouse)
	(crate-at crate26 warehouse)
	(crate-at crate27 warehouse)
	(crate-at crate28 warehouse)
	(crate-at crate29 warehouse)
	(crate-at crate30 warehouse)
	(crate-at crate31 warehouse)
	(crate-at crate32 warehouse)
	(crate-at crate33 warehouse)
	(crate-at crate34 warehouse)
	(crate-at crate35 warehouse)
	(crate-at crate36 warehouse)
	(crate-at crate37 warehouse)
	(crate-at crate38 warehouse)
	(crate-at crate39 warehouse)
	(crate-at crate40 warehouse)
	(crate-at crate41 warehouse)
	(crate-at crate42 warehouse)
	(crate-at crate43 warehouse)
	(crate-at crate44 warehouse)
	(crate-at crate45 warehouse)
	(crate-at crate46 warehouse)
	(crate-at crate47 warehouse)
	(crate-at crate48 warehouse)
	(crate-at crate49 warehouse)
	(crate-at crate50 warehouse)
	(crate-at crate51 warehouse)
	(crate-at crate52 warehouse)
	(crate-at crate53 warehouse)
	(crate-at crate54 warehouse)
	(crate-at crate55 warehouse)
	(crate-at crate56 warehouse)
	(crate-at crate57 warehouse)
	(crate-at crate58 warehouse)
	(crate-at crate59 warehouse)
	(crate-at crate60 warehouse)
	(crate-at crate61 warehouse)
	(crate-at crate62 warehouse)
	(crate-at crate63 warehouse)
	(crate-at crate64 warehouse)
	(crate-at crate65 warehouse)
	(crate-at crate66 warehouse)
	(crate-at crate67 warehouse)
	(crate-at crate68 warehouse)
	(crate-at crate69 warehouse)
	(crate-at crate70 warehouse)
	(crate-at crate71 warehouse)
	(crate-at crate72 warehouse)
	(crate-at crate73 warehouse)
	(crate-at crate74 warehouse)
	(crate-at crate75 warehouse)
	(crate-at crate76 warehouse)
	(crate-at crate77 warehouse)
	(crate-at crate78 warehouse)
	(crate-at crate79 warehouse)
	(crate-at crate80 warehouse)
	(crate-at crate81 warehouse)
	(crate-at crate82 warehouse)
	(crate-at crate83 warehouse)
	(crate-at crate84 warehouse)
	(crate-at crate85 warehouse)
	(crate-at crate86 warehouse)
	(crate-at crate87 warehouse)
	(empty-arm drone1 left)
	(empty-arm drone1 right)
	(content-crate food crate1)
	(content-crate food crate2)
	(content-crate food crate3)
	(content-crate food crate4)
	(content-crate food crate5)
	(content-crate food crate6)
	(content-crate food crate7)
	(content-crate food crate8)
	(content-crate food crate9)
	(content-crate food crate10)
	(content-crate food crate11)
	(content-crate food crate12)
	(content-crate food crate13)
	(content-crate food crate14)
	(content-crate food crate15)
	(content-crate food crate16)
	(content-crate food crate17)
	(content-crate food crate18)
	(content-crate food crate19)
	(content-crate food crate20)
	(content-crate food crate21)
	(content-crate food crate22)
	(content-crate food crate23)
	(content-crate food crate24)
	(content-crate food crate25)
	(content-crate food crate26)
	(content-crate food crate27)
	(content-crate food crate28)
	(content-crate food crate29)
	(content-crate food crate30)
	(content-crate food crate31)
	(content-crate food crate32)
	(content-crate food crate33)
	(content-crate food crate34)
	(content-crate food crate35)
	(content-crate food crate36)
	(content-crate food crate37)
	(content-crate food crate38)
	(content-crate food crate39)
	(content-crate food crate40)
	(content-crate food crate41)
	(content-crate food crate42)
	(content-crate food crate43)
	(content-crate food crate44)
	(content-crate food crate45)
	(content-crate food crate46)
	(content-crate food crate47)
	(content-crate food crate48)
	(content-crate food crate49)
	(content-crate food crate50)
	(content-crate food crate51)
	(content-crate food crate52)
	(content-crate food crate53)
	(content-crate food crate54)
	(content-crate food crate55)
	(content-crate food crate56)
	(content-crate food crate57)
	(content-crate food crate58)
	(content-crate food crate59)
	(content-crate food crate60)
	(content-crate food crate61)
	(content-crate food crate62)
	(content-crate food crate63)
	(content-crate food crate64)
	(content-crate food crate65)
	(content-crate food crate66)
	(content-crate food crate67)
	(content-crate food crate68)
	(content-crate medicine crate69)
	(content-crate medicine crate70)
	(content-crate medicine crate71)
	(content-crate medicine crate72)
	(content-crate medicine crate73)
	(content-crate medicine crate74)
	(content-crate medicine crate75)
	(content-crate medicine crate76)
	(content-crate medicine crate77)
	(content-crate medicine crate78)
	(content-crate medicine crate79)
	(content-crate medicine crate80)
	(content-crate medicine crate81)
	(content-crate medicine crate82)
	(content-crate medicine crate83)
	(content-crate medicine crate84)
	(content-crate medicine crate85)
	(content-crate medicine crate86)
	(content-crate medicine crate87)
	(person-at person1 loc51)
	(person-at person2 loc34)
	(person-at person3 loc82)
	(person-at person4 loc67)
	(person-at person5 loc3)
	(person-at person6 loc57)
	(person-at person7 loc78)
	(person-at person8 loc31)
	(person-at person9 loc17)
	(person-at person10 loc51)
	(person-at person11 loc62)
	(person-at person12 loc1)
	(person-at person13 loc27)
	(person-at person14 loc63)
	(person-at person15 loc21)
	(person-at person16 loc70)
	(person-at person17 loc56)
	(person-at person18 loc14)
	(person-at person19 loc15)
	(person-at person20 loc53)
	(person-at person21 loc46)
	(person-at person22 loc4)
	(person-at person23 loc26)
	(person-at person24 loc48)
	(person-at person25 loc2)
	(person-at person26 loc49)
	(person-at person27 loc58)
	(person-at person28 loc39)
	(person-at person29 loc40)
	(person-at person30 loc60)
	(person-at person31 loc9)
	(person-at person32 loc83)
	(person-at person33 loc84)
	(person-at person34 loc37)
	(person-at person35 loc34)
	(person-at person36 loc85)
	(person-at person37 loc79)
	(person-at person38 loc33)
	(person-at person39 loc76)
	(person-at person40 loc21)
	(person-at person41 loc7)
	(person-at person42 loc87)
	(person-at person43 loc46)
	(person-at person44 loc58)
	(person-at person45 loc53)
	(person-at person46 loc62)
	(person-at person47 loc12)
	(person-at person48 loc27)
	(person-at person49 loc61)
	(person-at person50 loc37)
	(person-at person51 loc84)
	(person-at person52 loc21)
	(person-at person53 loc46)
	(person-at person54 loc16)
	(person-at person55 loc71)
	(person-at person56 loc47)
	(person-at person57 loc57)
	(person-at person58 loc80)
	(person-at person59 loc44)
	(person-at person60 loc43)
	(person-at person61 loc67)
	(person-at person62 loc12)
	(person-at person63 loc84)
	(person-at person64 loc79)
	(person-at person65 loc74)
	(person-at person66 loc43)
	(person-at person67 loc20)
	(person-at person68 loc52)
	(person-at person69 loc28)
	(person-at person70 loc79)
	(person-at person71 loc27)
	(person-at person72 loc47)
	(person-at person73 loc19)
	(person-at person74 loc24)
	(person-at person75 loc33)
	(person-at person76 loc44)
	(person-at person77 loc35)
	(person-at person78 loc52)
	(person-at person79 loc54)
	(person-at person80 loc11)
	(person-at person81 loc36)
	(person-at person82 loc63)
	(person-at person83 loc64)
	(person-at person84 loc59)
	(person-at person85 loc23)
	(person-at person86 loc10)
	(person-at person87 loc84)
	(person-need person2 food)
	(person-need person4 food)
	(person-need person7 food)
	(person-need person7 medicine)
	(person-need person8 food)
	(person-need person10 food)
	(person-need person10 medicine)
	(person-need person11 food)
	(person-need person12 food)
	(person-need person13 food)
	(person-need person13 medicine)
	(person-need person14 food)
	(person-need person14 medicine)
	(person-need person15 food)
	(person-need person15 medicine)
	(person-need person17 food)
	(person-need person18 food)
	(person-need person18 medicine)
	(person-need person19 food)
	(person-need person21 food)
	(person-need person22 food)
	(person-need person23 food)
	(person-need person23 medicine)
	(person-need person24 food)
	(person-need person24 medicine)
	(person-need person25 medicine)
	(person-need person27 food)
	(person-need person27 medicine)
	(person-need person28 food)
	(person-need person29 food)
	(person-need person30 food)
	(person-need person31 food)
	(person-need person32 food)
	(person-need person33 food)
	(person-need person34 food)
	(person-need person36 food)
	(person-need person36 medicine)
	(person-need person37 food)
	(person-need person37 medicine)
	(person-need person38 food)
	(person-need person39 food)
	(person-need person40 food)
	(person-need person42 food)
	(person-need person44 food)
	(person-need person45 food)
	(person-need person46 food)
	(person-need person47 food)
	(person-need person47 medicine)
	(person-need person48 food)
	(person-need person49 food)
	(person-need person49 medicine)
	(person-need person50 food)
	(person-need person51 food)
	(person-need person52 food)
	(person-need person53 food)
	(person-need person54 food)
	(person-need person56 food)
	(person-need person57 food)
	(person-need person59 food)
	(person-need person59 medicine)
	(person-need person60 food)
	(person-need person61 food)
	(person-need person62 food)
	(person-need person63 food)
	(person-need person64 food)
	(person-need person65 food)
	(person-need person66 medicine)
	(person-need person67 food)
	(person-need person68 food)
	(person-need person68 medicine)
	(person-need person69 food)
	(person-need person70 food)
	(person-need person70 medicine)
	(person-need person71 food)
	(person-need person71 medicine)
	(person-need person74 food)
	(person-need person75 food)
	(person-need person76 food)
	(person-need person78 food)
	(person-need person79 food)
	(person-need person80 food)
	(person-need person81 food)
	(person-need person82 food)
	(person-need person83 food)
	(person-need person84 food)
	(person-need person85 food)
	(person-need person86 food)
)
(:goal (and
	(drone-at drone1 depot)
	(has-content-person person2 food)
	(has-content-person person4 food)
	(has-content-person person7 food)
	(has-content-person person7 medicine)
	(has-content-person person8 food)
	(has-content-person person10 food)
	(has-content-person person10 medicine)
	(has-content-person person11 food)
	(has-content-person person12 food)
	(has-content-person person13 food)
	(has-content-person person13 medicine)
	(has-content-person person14 food)
	(has-content-person person14 medicine)
	(has-content-person person15 food)
	(has-content-person person15 medicine)
	(has-content-person person17 food)
	(has-content-person person18 food)
	(has-content-person person18 medicine)
	(has-content-person person19 food)
	(has-content-person person21 food)
	(has-content-person person22 food)
	(has-content-person person23 food)
	(has-content-person person23 medicine)
	(has-content-person person24 food)
	(has-content-person person24 medicine)
	(has-content-person person25 medicine)
	(has-content-person person27 food)
	(has-content-person person27 medicine)
	(has-content-person person28 food)
	(has-content-person person29 food)
	(has-content-person person30 food)
	(has-content-person person31 food)
	(has-content-person person32 food)
	(has-content-person person33 food)
	(has-content-person person34 food)
	(has-content-person person36 food)
	(has-content-person person36 medicine)
	(has-content-person person37 food)
	(has-content-person person37 medicine)
	(has-content-person person38 food)
	(has-content-person person39 food)
	(has-content-person person40 food)
	(has-content-person person42 food)
	(has-content-person person44 food)
	(has-content-person person45 food)
	(has-content-person person46 food)
	(has-content-person person47 food)
	(has-content-person person47 medicine)
	(has-content-person person48 food)
	(has-content-person person49 food)
	(has-content-person person49 medicine)
	(has-content-person person50 food)
	(has-content-person person51 food)
	(has-content-person person52 food)
	(has-content-person person53 food)
	(has-content-person person54 food)
	(has-content-person person56 food)
	(has-content-person person57 food)
	(has-content-person person59 food)
	(has-content-person person59 medicine)
	(has-content-person person60 food)
	(has-content-person person61 food)
	(has-content-person person62 food)
	(has-content-person person63 food)
	(has-content-person person64 food)
	(has-content-person person65 food)
	(has-content-person person66 medicine)
	(has-content-person person67 food)
	(has-content-person person68 food)
	(has-content-person person68 medicine)
	(has-content-person person69 food)
	(has-content-person person70 food)
	(has-content-person person70 medicine)
	(has-content-person person71 food)
	(has-content-person person71 medicine)
	(has-content-person person74 food)
	(has-content-person person75 food)
	(has-content-person person76 food)
	(has-content-person person78 food)
	(has-content-person person79 food)
	(has-content-person person80 food)
	(has-content-person person81 food)
	(has-content-person person82 food)
	(has-content-person person83 food)
	(has-content-person person84 food)
	(has-content-person person85 food)
	(has-content-person person86 food)
))
)
