(define (problem drone_problem_d1_r0_l66_p66_c66_g66_ct2)
(:domain p1)
(:objects
	drone1 - drone
	depot - location
	warehouse - location
	loc1 - location
	loc2 - location
	loc3 - location
	loc4 - location
	loc5 - location
	loc6 - location
	loc7 - location
	loc8 - location
	loc9 - location
	loc10 - location
	loc11 - location
	loc12 - location
	loc13 - location
	loc14 - location
	loc15 - location
	loc16 - location
	loc17 - location
	loc18 - location
	loc19 - location
	loc20 - location
	loc21 - location
	loc22 - location
	loc23 - location
	loc24 - location
	loc25 - location
	loc26 - location
	loc27 - location
	loc28 - location
	loc29 - location
	loc30 - location
	loc31 - location
	loc32 - location
	loc33 - location
	loc34 - location
	loc35 - location
	loc36 - location
	loc37 - location
	loc38 - location
	loc39 - location
	loc40 - location
	loc41 - location
	loc42 - location
	loc43 - location
	loc44 - location
	loc45 - location
	loc46 - location
	loc47 - location
	loc48 - location
	loc49 - location
	loc50 - location
	loc51 - location
	loc52 - location
	loc53 - location
	loc54 - location
	loc55 - location
	loc56 - location
	loc57 - location
	loc58 - location
	loc59 - location
	loc60 - location
	loc61 - location
	loc62 - location
	loc63 - location
	loc64 - location
	loc65 - location
	loc66 - location
	crate1 - crate
	crate2 - crate
	crate3 - crate
	crate4 - crate
	crate5 - crate
	crate6 - crate
	crate7 - crate
	crate8 - crate
	crate9 - crate
	crate10 - crate
	crate11 - crate
	crate12 - crate
	crate13 - crate
	crate14 - crate
	crate15 - crate
	crate16 - crate
	crate17 - crate
	crate18 - crate
	crate19 - crate
	crate20 - crate
	crate21 - crate
	crate22 - crate
	crate23 - crate
	crate24 - crate
	crate25 - crate
	crate26 - crate
	crate27 - crate
	crate28 - crate
	crate29 - crate
	crate30 - crate
	crate31 - crate
	crate32 - crate
	crate33 - crate
	crate34 - crate
	crate35 - crate
	crate36 - crate
	crate37 - crate
	crate38 - crate
	crate39 - crate
	crate40 - crate
	crate41 - crate
	crate42 - crate
	crate43 - crate
	crate44 - crate
	crate45 - crate
	crate46 - crate
	crate47 - crate
	crate48 - crate
	crate49 - crate
	crate50 - crate
	crate51 - crate
	crate52 - crate
	crate53 - crate
	crate54 - crate
	crate55 - crate
	crate56 - crate
	crate57 - crate
	crate58 - crate
	crate59 - crate
	crate60 - crate
	crate61 - crate
	crate62 - crate
	crate63 - crate
	crate64 - crate
	crate65 - crate
	crate66 - crate
	food - content
	medicine - content
	person1 - person
	person2 - person
	person3 - person
	person4 - person
	person5 - person
	person6 - person
	person7 - person
	person8 - person
	person9 - person
	person10 - person
	person11 - person
	person12 - person
	person13 - person
	person14 - person
	person15 - person
	person16 - person
	person17 - person
	person18 - person
	person19 - person
	person20 - person
	person21 - person
	person22 - person
	person23 - person
	person24 - person
	person25 - person
	person26 - person
	person27 - person
	person28 - person
	person29 - person
	person30 - person
	person31 - person
	person32 - person
	person33 - person
	person34 - person
	person35 - person
	person36 - person
	person37 - person
	person38 - person
	person39 - person
	person40 - person
	person41 - person
	person42 - person
	person43 - person
	person44 - person
	person45 - person
	person46 - person
	person47 - person
	person48 - person
	person49 - person
	person50 - person
	person51 - person
	person52 - person
	person53 - person
	person54 - person
	person55 - person
	person56 - person
	person57 - person
	person58 - person
	person59 - person
	person60 - person
	person61 - person
	person62 - person
	person63 - person
	person64 - person
	person65 - person
	person66 - person
	left right - arm
)
(:init
	(drone-at drone1 depot)
	(crate-at crate1 warehouse)
	(crate-at crate2 warehouse)
	(crate-at crate3 warehouse)
	(crate-at crate4 warehouse)
	(crate-at crate5 warehouse)
	(crate-at crate6 warehouse)
	(crate-at crate7 warehouse)
	(crate-at crate8 warehouse)
	(crate-at crate9 warehouse)
	(crate-at crate10 warehouse)
	(crate-at crate11 warehouse)
	(crate-at crate12 warehouse)
	(crate-at crate13 warehouse)
	(crate-at crate14 warehouse)
	(crate-at crate15 warehouse)
	(crate-at crate16 warehouse)
	(crate-at crate17 warehouse)
	(crate-at crate18 warehouse)
	(crate-at crate19 warehouse)
	(crate-at crate20 warehouse)
	(crate-at crate21 warehouse)
	(crate-at crate22 warehouse)
	(crate-at crate23 warehouse)
	(crate-at crate24 warehouse)
	(crate-at crate25 warehouse)
	(crate-at crate26 warehouse)
	(crate-at crate27 warehouse)
	(crate-at crate28 warehouse)
	(crate-at crate29 warehouse)
	(crate-at crate30 warehouse)
	(crate-at crate31 warehouse)
	(crate-at crate32 warehouse)
	(crate-at crate33 warehouse)
	(crate-at crate34 warehouse)
	(crate-at crate35 warehouse)
	(crate-at crate36 warehouse)
	(crate-at crate37 warehouse)
	(crate-at crate38 warehouse)
	(crate-at crate39 warehouse)
	(crate-at crate40 warehouse)
	(crate-at crate41 warehouse)
	(crate-at crate42 warehouse)
	(crate-at crate43 warehouse)
	(crate-at crate44 warehouse)
	(crate-at crate45 warehouse)
	(crate-at crate46 warehouse)
	(crate-at crate47 warehouse)
	(crate-at crate48 warehouse)
	(crate-at crate49 warehouse)
	(crate-at crate50 warehouse)
	(crate-at crate51 warehouse)
	(crate-at crate52 warehouse)
	(crate-at crate53 warehouse)
	(crate-at crate54 warehouse)
	(crate-at crate55 warehouse)
	(crate-at crate56 warehouse)
	(crate-at crate57 warehouse)
	(crate-at crate58 warehouse)
	(crate-at crate59 warehouse)
	(crate-at crate60 warehouse)
	(crate-at crate61 warehouse)
	(crate-at crate62 warehouse)
	(crate-at crate63 warehouse)
	(crate-at crate64 warehouse)
	(crate-at crate65 warehouse)
	(crate-at crate66 warehouse)
	(empty-arm drone1 left)
	(empty-arm drone1 right)
	(content-crate food crate1)
	(content-crate food crate2)
	(content-crate food crate3)
	(content-crate food crate4)
	(content-crate food crate5)
	(content-crate food crate6)
	(content-crate food crate7)
	(content-crate food crate8)
	(content-crate food crate9)
	(content-crate food crate10)
	(content-crate food crate11)
	(content-crate food crate12)
	(content-crate food crate13)
	(content-crate food crate14)
	(content-crate food crate15)
	(content-crate food crate16)
	(content-crate food crate17)
	(content-crate food crate18)
	(content-crate food crate19)
	(content-crate food crate20)
	(content-crate food crate21)
	(content-crate food crate22)
	(content-crate food crate23)
	(content-crate food crate24)
	(content-crate food crate25)
	(content-crate food crate26)
	(content-crate food crate27)
	(content-crate food crate28)
	(content-crate food crate29)
	(content-crate food crate30)
	(content-crate food crate31)
	(content-crate food crate32)
	(content-crate food crate33)
	(content-crate food crate34)
	(content-crate food crate35)
	(content-crate food crate36)
	(content-crate food crate37)
	(content-crate food crate38)
	(content-crate food crate39)
	(content-crate food crate40)
	(content-crate food crate41)
	(content-crate food crate42)
	(content-crate food crate43)
	(content-crate food crate44)
	(content-crate food crate45)
	(content-crate food crate46)
	(content-crate food crate47)
	(content-crate food crate48)
	(content-crate medicine crate49)
	(content-crate medicine crate50)
	(content-crate medicine crate51)
	(content-crate medicine crate52)
	(content-crate medicine crate53)
	(content-crate medicine crate54)
	(content-crate medicine crate55)
	(content-crate medicine crate56)
	(content-crate medicine crate57)
	(content-crate medicine crate58)
	(content-crate medicine crate59)
	(content-crate medicine crate60)
	(content-crate medicine crate61)
	(content-crate medicine crate62)
	(content-crate medicine crate63)
	(content-crate medicine crate64)
	(content-crate medicine crate65)
	(content-crate medicine crate66)
	(person-at person1 loc5)
	(person-at person2 loc37)
	(person-at person3 loc62)
	(person-at person4 loc32)
	(person-at person5 loc61)
	(person-at person6 loc9)
	(person-at person7 loc2)
	(person-at person8 loc57)
	(person-at person9 loc14)
	(person-at person10 loc5)
	(person-at person11 loc34)
	(person-at person12 loc1)
	(person-at person13 loc66)
	(person-at person14 loc52)
	(person-at person15 loc6)
	(person-at person16 loc38)
	(person-at person17 loc34)
	(person-at person18 loc8)
	(person-at person19 loc35)
	(person-at person20 loc33)
	(person-at person21 loc65)
	(person-at person22 loc63)
	(person-at person23 loc53)
	(person-at person24 loc63)
	(person-at person25 loc25)
	(person-at person26 loc12)
	(person-at person27 loc31)
	(person-at person28 loc13)
	(person-at person29 loc57)
	(person-at person30 loc27)
	(person-at person31 loc25)
	(person-at person32 loc53)
	(person-at person33 loc53)
	(person-at person34 loc27)
	(person-at person35 loc22)
	(person-at person36 loc5)
	(person-at person37 loc40)
	(person-at person38 loc37)
	(person-at person39 loc6)
	(person-at person40 loc41)
	(person-at person41 loc46)
	(person-at person42 loc19)
	(person-at person43 loc12)
	(person-at person44 loc47)
	(person-at person45 loc28)
	(person-at person46 loc49)
	(person-at person47 loc10)
	(person-at person48 loc16)
	(person-at person49 loc17)
	(person-at person50 loc52)
	(person-at person51 loc19)
	(person-at person52 loc28)
	(person-at person53 loc58)
	(person-at person54 loc57)
	(person-at person55 loc58)
	(person-at person56 loc16)
	(person-at person57 loc43)
	(person-at person58 loc23)
	(person-at person59 loc60)
	(person-at person60 loc24)
	(person-at person61 loc61)
	(person-at person62 loc62)
	(person-at person63 loc39)
	(person-at person64 loc11)
	(person-at person65 loc18)
	(person-at person66 loc1)
	(person-need person1 food)
	(person-need person3 food)
	(person-need person4 food)
	(person-need person7 food)
	(person-need person7 medicine)
	(person-need person8 food)
	(person-need person9 food)
	(person-need person11 medicine)
	(person-need person14 food)
	(person-need person15 food)
	(person-need person16 food)
	(person-need person16 medicine)
	(person-need person17 food)
	(person-need person18 food)
	(person-need person19 food)
	(person-need person19 medicine)
	(person-need person20 medicine)
	(person-need person21 food)
	(person-need person22 food)
	(person-need person22 medicine)
	(person-need person24 food)
	(person-need person25 food)
	(person-need person26 food)
	(person-need person27 food)
	(person-need person28 food)
	(person-need person28 medicine)
	(person-need person29 food)
	(person-need person29 medicine)
	(person-need person30 food)
	(person-need person30 medicine)
	(person-need person31 food)
	(person-need person33 food)
	(person-need person34 food)
	(person-need person35 food)
	(person-need person36 food)
	(person-need person36 medicine)
	(person-need person37 food)
	(person-need person40 food)
	(person-need person41 food)
	(person-need person42 food)
	(person-need person44 food)
	(person-need person45 food)
	(person-need person45 medicine)
	(person-need person47 food)
	(person-need person48 food)
	(person-need person49 food)
	(person-need person52 food)
	(person-need person53 food)
	(person-need person53 medicine)
	(person-need person54 food)
	(person-need person55 food)
	(person-need person55 medicine)
	(person-need person56 food)
	(person-need person56 medicine)
	(person-need person57 food)
	(person-need person58 food)
	(person-need person59 food)
	(person-need person59 medicine)
	(person-need person60 medicine)
	(person-need person61 food)
	(person-need person62 food)
	(person-need person63 food)
	(person-need person64 food)
	(person-need person64 medicine)
	(person-need person65 food)
	(person-need person65 medicine)
)
(:goal (and
	(drone-at drone1 depot)
	(has-content-person person1 food)
	(has-content-person person3 food)
	(has-content-person person4 food)
	(has-content-person person7 food)
	(has-content-person person7 medicine)
	(has-content-person person8 food)
	(has-content-person person9 food)
	(has-content-person person11 medicine)
	(has-content-person person14 food)
	(has-content-person person15 food)
	(has-content-person person16 food)
	(has-content-person person16 medicine)
	(has-content-person person17 food)
	(has-content-person person18 food)
	(has-content-person person19 food)
	(has-content-person person19 medicine)
	(has-content-person person20 medicine)
	(has-content-person person21 food)
	(has-content-person person22 food)
	(has-content-person person22 medicine)
	(has-content-person person24 food)
	(has-content-person person25 food)
	(has-content-person person26 food)
	(has-content-person person27 food)
	(has-content-person person28 food)
	(has-content-person person28 medicine)
	(has-content-person person29 food)
	(has-content-person person29 medicine)
	(has-content-person person30 food)
	(has-content-person person30 medicine)
	(has-content-person person31 food)
	(has-content-person person33 food)
	(has-content-person person34 food)
	(has-content-person person35 food)
	(has-content-person person36 food)
	(has-content-person person36 medicine)
	(has-content-person person37 food)
	(has-content-person person40 food)
	(has-content-person person41 food)
	(has-content-person person42 food)
	(has-content-person person44 food)
	(has-content-person person45 food)
	(has-content-person person45 medicine)
	(has-content-person person47 food)
	(has-content-person person48 food)
	(has-content-person person49 food)
	(has-content-person person52 food)
	(has-content-person person53 food)
	(has-content-person person53 medicine)
	(has-content-person person54 food)
	(has-content-person person55 food)
	(has-content-person person55 medicine)
	(has-content-person person56 food)
	(has-content-person person56 medicine)
	(has-content-person person57 food)
	(has-content-person person58 food)
	(has-content-person person59 food)
	(has-content-person person59 medicine)
	(has-content-person person60 medicine)
	(has-content-person person61 food)
	(has-content-person person62 food)
	(has-content-person person63 food)
	(has-content-person person64 food)
	(has-content-person person64 medicine)
	(has-content-person person65 food)
	(has-content-person person65 medicine)
))
)
