(define (problem drone_problem_d1_r0_l20_p20_c20_g20_ct2)
(:domain p1)
(:objects
	drone1 - drone
	depot - location
	loc1 - location
	loc2 - location
	loc3 - location
	loc4 - location
	loc5 - location
	loc6 - location
	loc7 - location
	loc8 - location
	loc9 - location
	loc10 - location
	loc11 - location
	loc12 - location
	loc13 - location
	loc14 - location
	loc15 - location
	loc16 - location
	loc17 - location
	loc18 - location
	loc19 - location
	loc20 - location
	crate1 - crate
	crate2 - crate
	crate3 - crate
	crate4 - crate
	crate5 - crate
	crate6 - crate
	crate7 - crate
	crate8 - crate
	crate9 - crate
	crate10 - crate
	crate11 - crate
	crate12 - crate
	crate13 - crate
	crate14 - crate
	crate15 - crate
	crate16 - crate
	crate17 - crate
	crate18 - crate
	crate19 - crate
	crate20 - crate
	food - content
	medicine - content
	person1 - person
	person2 - person
	person3 - person
	person4 - person
	person5 - person
	person6 - person
	person7 - person
	person8 - person
	person9 - person
	person10 - person
	person11 - person
	person12 - person
	person13 - person
	person14 - person
	person15 - person
	person16 - person
	person17 - person
	person18 - person
	person19 - person
	person20 - person
	left right - arm
)
(:init
	(drone-at drone1 depot)
	(crate-at crate1 depot)
	(crate-at crate2 depot)
	(crate-at crate3 depot)
	(crate-at crate4 depot)
	(crate-at crate5 depot)
	(crate-at crate6 depot)
	(crate-at crate7 depot)
	(crate-at crate8 depot)
	(crate-at crate9 depot)
	(crate-at crate10 depot)
	(crate-at crate11 depot)
	(crate-at crate12 depot)
	(crate-at crate13 depot)
	(crate-at crate14 depot)
	(crate-at crate15 depot)
	(crate-at crate16 depot)
	(crate-at crate17 depot)
	(crate-at crate18 depot)
	(crate-at crate19 depot)
	(crate-at crate20 depot)
	(empty-arm left)
	(empty-arm right)
	(content-crate food crate1)
	(content-crate food crate2)
	(content-crate food crate3)
	(content-crate food crate4)
	(content-crate food crate5)
	(content-crate food crate6)
	(content-crate food crate7)
	(content-crate food crate8)
	(content-crate food crate9)
	(content-crate food crate10)
	(content-crate food crate11)
	(content-crate food crate12)
	(content-crate food crate13)
	(content-crate food crate14)
	(content-crate food crate15)
	(content-crate food crate16)
	(content-crate food crate17)
	(content-crate food crate18)
	(content-crate food crate19)
	(content-crate medicine crate20)
	(person-at person1 loc12)
	(person-at person2 loc9)
	(person-at person3 loc2)
	(person-at person4 loc20)
	(person-at person5 loc7)
	(person-at person6 loc6)
	(person-at person7 loc4)
	(person-at person8 loc19)
	(person-at person9 loc10)
	(person-at person10 loc10)
	(person-at person11 loc1)
	(person-at person12 loc3)
	(person-at person13 loc11)
	(person-at person14 loc6)
	(person-at person15 loc11)
	(person-at person16 loc5)
	(person-at person17 loc2)
	(person-at person18 loc6)
	(person-at person19 loc5)
	(person-at person20 loc5)
	(person-need person1 food)
	(person-need person2 food)
	(person-need person3 food)
	(person-need person4 food)
	(person-need person5 food)
	(person-need person6 food)
	(person-need person6 medicine)
	(person-need person7 food)
	(person-need person8 food)
	(person-need person9 food)
	(person-need person10 food)
	(person-need person11 food)
	(person-need person12 food)
	(person-need person13 food)
	(person-need person14 food)
	(person-need person15 food)
	(person-need person16 food)
	(person-need person17 food)
	(person-need person18 food)
	(person-need person20 food)
)
(:goal (and
	(drone-at drone1 depot)
	(has-content-person person1 food)
	(has-content-person person2 food)
	(has-content-person person3 food)
	(has-content-person person4 food)
	(has-content-person person5 food)
	(has-content-person person6 food)
	(has-content-person person6 medicine)
	(has-content-person person7 food)
	(has-content-person person8 food)
	(has-content-person person9 food)
	(has-content-person person10 food)
	(has-content-person person11 food)
	(has-content-person person12 food)
	(has-content-person person13 food)
	(has-content-person person14 food)
	(has-content-person person15 food)
	(has-content-person person16 food)
	(has-content-person person17 food)
	(has-content-person person18 food)
	(has-content-person person20 food)
))
)
