(define (problem drone_problem_d1_r0_l51_p51_c51_g51_ct2)
(:domain p1)
(:objects
	drone1 - drone
	depot - location
	loc1 - location
	loc2 - location
	loc3 - location
	loc4 - location
	loc5 - location
	loc6 - location
	loc7 - location
	loc8 - location
	loc9 - location
	loc10 - location
	loc11 - location
	loc12 - location
	loc13 - location
	loc14 - location
	loc15 - location
	loc16 - location
	loc17 - location
	loc18 - location
	loc19 - location
	loc20 - location
	loc21 - location
	loc22 - location
	loc23 - location
	loc24 - location
	loc25 - location
	loc26 - location
	loc27 - location
	loc28 - location
	loc29 - location
	loc30 - location
	loc31 - location
	loc32 - location
	loc33 - location
	loc34 - location
	loc35 - location
	loc36 - location
	loc37 - location
	loc38 - location
	loc39 - location
	loc40 - location
	loc41 - location
	loc42 - location
	loc43 - location
	loc44 - location
	loc45 - location
	loc46 - location
	loc47 - location
	loc48 - location
	loc49 - location
	loc50 - location
	loc51 - location
	crate1 - crate
	crate2 - crate
	crate3 - crate
	crate4 - crate
	crate5 - crate
	crate6 - crate
	crate7 - crate
	crate8 - crate
	crate9 - crate
	crate10 - crate
	crate11 - crate
	crate12 - crate
	crate13 - crate
	crate14 - crate
	crate15 - crate
	crate16 - crate
	crate17 - crate
	crate18 - crate
	crate19 - crate
	crate20 - crate
	crate21 - crate
	crate22 - crate
	crate23 - crate
	crate24 - crate
	crate25 - crate
	crate26 - crate
	crate27 - crate
	crate28 - crate
	crate29 - crate
	crate30 - crate
	crate31 - crate
	crate32 - crate
	crate33 - crate
	crate34 - crate
	crate35 - crate
	crate36 - crate
	crate37 - crate
	crate38 - crate
	crate39 - crate
	crate40 - crate
	crate41 - crate
	crate42 - crate
	crate43 - crate
	crate44 - crate
	crate45 - crate
	crate46 - crate
	crate47 - crate
	crate48 - crate
	crate49 - crate
	crate50 - crate
	crate51 - crate
	food - content
	medicine - content
	person1 - person
	person2 - person
	person3 - person
	person4 - person
	person5 - person
	person6 - person
	person7 - person
	person8 - person
	person9 - person
	person10 - person
	person11 - person
	person12 - person
	person13 - person
	person14 - person
	person15 - person
	person16 - person
	person17 - person
	person18 - person
	person19 - person
	person20 - person
	person21 - person
	person22 - person
	person23 - person
	person24 - person
	person25 - person
	person26 - person
	person27 - person
	person28 - person
	person29 - person
	person30 - person
	person31 - person
	person32 - person
	person33 - person
	person34 - person
	person35 - person
	person36 - person
	person37 - person
	person38 - person
	person39 - person
	person40 - person
	person41 - person
	person42 - person
	person43 - person
	person44 - person
	person45 - person
	person46 - person
	person47 - person
	person48 - person
	person49 - person
	person50 - person
	person51 - person
	left right - arm
)
(:init
	(drone-at drone1 depot)
	(crate-at crate1 depot)
	(crate-at crate2 depot)
	(crate-at crate3 depot)
	(crate-at crate4 depot)
	(crate-at crate5 depot)
	(crate-at crate6 depot)
	(crate-at crate7 depot)
	(crate-at crate8 depot)
	(crate-at crate9 depot)
	(crate-at crate10 depot)
	(crate-at crate11 depot)
	(crate-at crate12 depot)
	(crate-at crate13 depot)
	(crate-at crate14 depot)
	(crate-at crate15 depot)
	(crate-at crate16 depot)
	(crate-at crate17 depot)
	(crate-at crate18 depot)
	(crate-at crate19 depot)
	(crate-at crate20 depot)
	(crate-at crate21 depot)
	(crate-at crate22 depot)
	(crate-at crate23 depot)
	(crate-at crate24 depot)
	(crate-at crate25 depot)
	(crate-at crate26 depot)
	(crate-at crate27 depot)
	(crate-at crate28 depot)
	(crate-at crate29 depot)
	(crate-at crate30 depot)
	(crate-at crate31 depot)
	(crate-at crate32 depot)
	(crate-at crate33 depot)
	(crate-at crate34 depot)
	(crate-at crate35 depot)
	(crate-at crate36 depot)
	(crate-at crate37 depot)
	(crate-at crate38 depot)
	(crate-at crate39 depot)
	(crate-at crate40 depot)
	(crate-at crate41 depot)
	(crate-at crate42 depot)
	(crate-at crate43 depot)
	(crate-at crate44 depot)
	(crate-at crate45 depot)
	(crate-at crate46 depot)
	(crate-at crate47 depot)
	(crate-at crate48 depot)
	(crate-at crate49 depot)
	(crate-at crate50 depot)
	(crate-at crate51 depot)
	(empty-arm left)
	(empty-arm right)
	(content-crate food crate1)
	(content-crate food crate2)
	(content-crate food crate3)
	(content-crate food crate4)
	(content-crate food crate5)
	(content-crate food crate6)
	(content-crate food crate7)
	(content-crate food crate8)
	(content-crate food crate9)
	(content-crate food crate10)
	(content-crate food crate11)
	(content-crate food crate12)
	(content-crate food crate13)
	(content-crate food crate14)
	(content-crate food crate15)
	(content-crate food crate16)
	(content-crate food crate17)
	(content-crate food crate18)
	(content-crate food crate19)
	(content-crate food crate20)
	(content-crate food crate21)
	(content-crate food crate22)
	(content-crate food crate23)
	(content-crate food crate24)
	(content-crate food crate25)
	(content-crate food crate26)
	(content-crate food crate27)
	(content-crate food crate28)
	(content-crate food crate29)
	(content-crate food crate30)
	(content-crate food crate31)
	(content-crate food crate32)
	(content-crate food crate33)
	(content-crate food crate34)
	(content-crate food crate35)
	(content-crate food crate36)
	(content-crate food crate37)
	(content-crate food crate38)
	(content-crate food crate39)
	(content-crate food crate40)
	(content-crate food crate41)
	(content-crate food crate42)
	(content-crate food crate43)
	(content-crate food crate44)
	(content-crate food crate45)
	(content-crate food crate46)
	(content-crate food crate47)
	(content-crate food crate48)
	(content-crate medicine crate49)
	(content-crate medicine crate50)
	(content-crate medicine crate51)
	(person-at person1 loc29)
	(person-at person2 loc34)
	(person-at person3 loc34)
	(person-at person4 loc6)
	(person-at person5 loc9)
	(person-at person6 loc5)
	(person-at person7 loc49)
	(person-at person8 loc7)
	(person-at person9 loc9)
	(person-at person10 loc6)
	(person-at person11 loc12)
	(person-at person12 loc33)
	(person-at person13 loc24)
	(person-at person14 loc8)
	(person-at person15 loc51)
	(person-at person16 loc50)
	(person-at person17 loc39)
	(person-at person18 loc33)
	(person-at person19 loc25)
	(person-at person20 loc44)
	(person-at person21 loc24)
	(person-at person22 loc23)
	(person-at person23 loc23)
	(person-at person24 loc40)
	(person-at person25 loc16)
	(person-at person26 loc37)
	(person-at person27 loc11)
	(person-at person28 loc47)
	(person-at person29 loc33)
	(person-at person30 loc46)
	(person-at person31 loc35)
	(person-at person32 loc44)
	(person-at person33 loc18)
	(person-at person34 loc11)
	(person-at person35 loc6)
	(person-at person36 loc51)
	(person-at person37 loc5)
	(person-at person38 loc13)
	(person-at person39 loc46)
	(person-at person40 loc15)
	(person-at person41 loc46)
	(person-at person42 loc28)
	(person-at person43 loc15)
	(person-at person44 loc21)
	(person-at person45 loc1)
	(person-at person46 loc46)
	(person-at person47 loc5)
	(person-at person48 loc46)
	(person-at person49 loc25)
	(person-at person50 loc15)
	(person-at person51 loc42)
	(person-need person1 food)
	(person-need person2 food)
	(person-need person3 food)
	(person-need person4 food)
	(person-need person5 food)
	(person-need person6 food)
	(person-need person7 food)
	(person-need person7 medicine)
	(person-need person8 food)
	(person-need person9 food)
	(person-need person10 food)
	(person-need person10 medicine)
	(person-need person11 food)
	(person-need person12 food)
	(person-need person13 food)
	(person-need person14 food)
	(person-need person15 food)
	(person-need person16 food)
	(person-need person17 food)
	(person-need person18 food)
	(person-need person19 food)
	(person-need person20 food)
	(person-need person21 food)
	(person-need person22 food)
	(person-need person23 food)
	(person-need person24 food)
	(person-need person25 food)
	(person-need person26 food)
	(person-need person27 food)
	(person-need person28 food)
	(person-need person29 food)
	(person-need person30 food)
	(person-need person31 food)
	(person-need person32 food)
	(person-need person33 food)
	(person-need person35 food)
	(person-need person36 food)
	(person-need person37 food)
	(person-need person38 food)
	(person-need person39 food)
	(person-need person40 food)
	(person-need person40 medicine)
	(person-need person41 food)
	(person-need person42 food)
	(person-need person44 food)
	(person-need person45 food)
	(person-need person46 food)
	(person-need person47 food)
	(person-need person49 food)
	(person-need person50 food)
	(person-need person51 food)
)
(:goal (and
	(drone-at drone1 depot)
	(has-content-person person1 food)
	(has-content-person person2 food)
	(has-content-person person3 food)
	(has-content-person person4 food)
	(has-content-person person5 food)
	(has-content-person person6 food)
	(has-content-person person7 food)
	(has-content-person person7 medicine)
	(has-content-person person8 food)
	(has-content-person person9 food)
	(has-content-person person10 food)
	(has-content-person person10 medicine)
	(has-content-person person11 food)
	(has-content-person person12 food)
	(has-content-person person13 food)
	(has-content-person person14 food)
	(has-content-person person15 food)
	(has-content-person person16 food)
	(has-content-person person17 food)
	(has-content-person person18 food)
	(has-content-person person19 food)
	(has-content-person person20 food)
	(has-content-person person21 food)
	(has-content-person person22 food)
	(has-content-person person23 food)
	(has-content-person person24 food)
	(has-content-person person25 food)
	(has-content-person person26 food)
	(has-content-person person27 food)
	(has-content-person person28 food)
	(has-content-person person29 food)
	(has-content-person person30 food)
	(has-content-person person31 food)
	(has-content-person person32 food)
	(has-content-person person33 food)
	(has-content-person person35 food)
	(has-content-person person36 food)
	(has-content-person person37 food)
	(has-content-person person38 food)
	(has-content-person person39 food)
	(has-content-person person40 food)
	(has-content-person person40 medicine)
	(has-content-person person41 food)
	(has-content-person person42 food)
	(has-content-person person44 food)
	(has-content-person person45 food)
	(has-content-person person46 food)
	(has-content-person person47 food)
	(has-content-person person49 food)
	(has-content-person person50 food)
	(has-content-person person51 food)
))
)
