(define (problem drone_problem_d1_r0_l35_p35_c35_g35_ct2)
(:domain p1)
(:objects
	drone1 - drone
	depot - location
	loc1 - location
	loc2 - location
	loc3 - location
	loc4 - location
	loc5 - location
	loc6 - location
	loc7 - location
	loc8 - location
	loc9 - location
	loc10 - location
	loc11 - location
	loc12 - location
	loc13 - location
	loc14 - location
	loc15 - location
	loc16 - location
	loc17 - location
	loc18 - location
	loc19 - location
	loc20 - location
	loc21 - location
	loc22 - location
	loc23 - location
	loc24 - location
	loc25 - location
	loc26 - location
	loc27 - location
	loc28 - location
	loc29 - location
	loc30 - location
	loc31 - location
	loc32 - location
	loc33 - location
	loc34 - location
	loc35 - location
	crate1 - crate
	crate2 - crate
	crate3 - crate
	crate4 - crate
	crate5 - crate
	crate6 - crate
	crate7 - crate
	crate8 - crate
	crate9 - crate
	crate10 - crate
	crate11 - crate
	crate12 - crate
	crate13 - crate
	crate14 - crate
	crate15 - crate
	crate16 - crate
	crate17 - crate
	crate18 - crate
	crate19 - crate
	crate20 - crate
	crate21 - crate
	crate22 - crate
	crate23 - crate
	crate24 - crate
	crate25 - crate
	crate26 - crate
	crate27 - crate
	crate28 - crate
	crate29 - crate
	crate30 - crate
	crate31 - crate
	crate32 - crate
	crate33 - crate
	crate34 - crate
	crate35 - crate
	food - content
	medicine - content
	person1 - person
	person2 - person
	person3 - person
	person4 - person
	person5 - person
	person6 - person
	person7 - person
	person8 - person
	person9 - person
	person10 - person
	person11 - person
	person12 - person
	person13 - person
	person14 - person
	person15 - person
	person16 - person
	person17 - person
	person18 - person
	person19 - person
	person20 - person
	person21 - person
	person22 - person
	person23 - person
	person24 - person
	person25 - person
	person26 - person
	person27 - person
	person28 - person
	person29 - person
	person30 - person
	person31 - person
	person32 - person
	person33 - person
	person34 - person
	person35 - person
	left right - arm
)
(:init
	(drone-at drone1 depot)
	(crate-at crate1 depot)
	(crate-at crate2 depot)
	(crate-at crate3 depot)
	(crate-at crate4 depot)
	(crate-at crate5 depot)
	(crate-at crate6 depot)
	(crate-at crate7 depot)
	(crate-at crate8 depot)
	(crate-at crate9 depot)
	(crate-at crate10 depot)
	(crate-at crate11 depot)
	(crate-at crate12 depot)
	(crate-at crate13 depot)
	(crate-at crate14 depot)
	(crate-at crate15 depot)
	(crate-at crate16 depot)
	(crate-at crate17 depot)
	(crate-at crate18 depot)
	(crate-at crate19 depot)
	(crate-at crate20 depot)
	(crate-at crate21 depot)
	(crate-at crate22 depot)
	(crate-at crate23 depot)
	(crate-at crate24 depot)
	(crate-at crate25 depot)
	(crate-at crate26 depot)
	(crate-at crate27 depot)
	(crate-at crate28 depot)
	(crate-at crate29 depot)
	(crate-at crate30 depot)
	(crate-at crate31 depot)
	(crate-at crate32 depot)
	(crate-at crate33 depot)
	(crate-at crate34 depot)
	(crate-at crate35 depot)
	(empty-arm left)
	(empty-arm right)
	(content-crate food crate1)
	(content-crate food crate2)
	(content-crate food crate3)
	(content-crate food crate4)
	(content-crate food crate5)
	(content-crate food crate6)
	(content-crate food crate7)
	(content-crate food crate8)
	(content-crate food crate9)
	(content-crate food crate10)
	(content-crate food crate11)
	(content-crate food crate12)
	(content-crate food crate13)
	(content-crate food crate14)
	(content-crate food crate15)
	(content-crate food crate16)
	(content-crate food crate17)
	(content-crate food crate18)
	(content-crate food crate19)
	(content-crate food crate20)
	(content-crate food crate21)
	(content-crate medicine crate22)
	(content-crate medicine crate23)
	(content-crate medicine crate24)
	(content-crate medicine crate25)
	(content-crate medicine crate26)
	(content-crate medicine crate27)
	(content-crate medicine crate28)
	(content-crate medicine crate29)
	(content-crate medicine crate30)
	(content-crate medicine crate31)
	(content-crate medicine crate32)
	(content-crate medicine crate33)
	(content-crate medicine crate34)
	(content-crate medicine crate35)
	(person-at person1 loc3)
	(person-at person2 loc9)
	(person-at person3 loc33)
	(person-at person4 loc15)
	(person-at person5 loc9)
	(person-at person6 loc20)
	(person-at person7 loc32)
	(person-at person8 loc10)
	(person-at person9 loc16)
	(person-at person10 loc14)
	(person-at person11 loc13)
	(person-at person12 loc32)
	(person-at person13 loc21)
	(person-at person14 loc6)
	(person-at person15 loc1)
	(person-at person16 loc20)
	(person-at person17 loc16)
	(person-at person18 loc12)
	(person-at person19 loc32)
	(person-at person20 loc29)
	(person-at person21 loc1)
	(person-at person22 loc17)
	(person-at person23 loc18)
	(person-at person24 loc10)
	(person-at person25 loc7)
	(person-at person26 loc22)
	(person-at person27 loc20)
	(person-at person28 loc19)
	(person-at person29 loc2)
	(person-at person30 loc12)
	(person-at person31 loc20)
	(person-at person32 loc14)
	(person-at person33 loc15)
	(person-at person34 loc31)
	(person-at person35 loc27)
	(person-need person2 food)
	(person-need person3 food)
	(person-need person4 medicine)
	(person-need person5 food)
	(person-need person5 medicine)
	(person-need person6 food)
	(person-need person7 food)
	(person-need person8 food)
	(person-need person8 medicine)
	(person-need person10 food)
	(person-need person10 medicine)
	(person-need person11 food)
	(person-need person12 food)
	(person-need person12 medicine)
	(person-need person13 food)
	(person-need person13 medicine)
	(person-need person14 food)
	(person-need person15 medicine)
	(person-need person19 medicine)
	(person-need person20 food)
	(person-need person21 food)
	(person-need person22 medicine)
	(person-need person23 food)
	(person-need person23 medicine)
	(person-need person24 food)
	(person-need person24 medicine)
	(person-need person25 food)
	(person-need person26 food)
	(person-need person27 food)
	(person-need person28 medicine)
	(person-need person29 food)
	(person-need person30 food)
	(person-need person33 medicine)
	(person-need person34 food)
	(person-need person35 medicine)
)
(:goal (and
	(drone-at drone1 depot)
	(has-content-person person2 food)
	(has-content-person person3 food)
	(has-content-person person4 medicine)
	(has-content-person person5 food)
	(has-content-person person5 medicine)
	(has-content-person person6 food)
	(has-content-person person7 food)
	(has-content-person person8 food)
	(has-content-person person8 medicine)
	(has-content-person person10 food)
	(has-content-person person10 medicine)
	(has-content-person person11 food)
	(has-content-person person12 food)
	(has-content-person person12 medicine)
	(has-content-person person13 food)
	(has-content-person person13 medicine)
	(has-content-person person14 food)
	(has-content-person person15 medicine)
	(has-content-person person19 medicine)
	(has-content-person person20 food)
	(has-content-person person21 food)
	(has-content-person person22 medicine)
	(has-content-person person23 food)
	(has-content-person person23 medicine)
	(has-content-person person24 food)
	(has-content-person person24 medicine)
	(has-content-person person25 food)
	(has-content-person person26 food)
	(has-content-person person27 food)
	(has-content-person person28 medicine)
	(has-content-person person29 food)
	(has-content-person person30 food)
	(has-content-person person33 medicine)
	(has-content-person person34 food)
	(has-content-person person35 medicine)
))
)
