(define (problem drone_problem_d1_r0_l48_p48_c48_g48_ct2)
(:domain p1)
(:objects
	drone1 - drone
	depot - location
	warehouse - location
	loc1 - location
	loc2 - location
	loc3 - location
	loc4 - location
	loc5 - location
	loc6 - location
	loc7 - location
	loc8 - location
	loc9 - location
	loc10 - location
	loc11 - location
	loc12 - location
	loc13 - location
	loc14 - location
	loc15 - location
	loc16 - location
	loc17 - location
	loc18 - location
	loc19 - location
	loc20 - location
	loc21 - location
	loc22 - location
	loc23 - location
	loc24 - location
	loc25 - location
	loc26 - location
	loc27 - location
	loc28 - location
	loc29 - location
	loc30 - location
	loc31 - location
	loc32 - location
	loc33 - location
	loc34 - location
	loc35 - location
	loc36 - location
	loc37 - location
	loc38 - location
	loc39 - location
	loc40 - location
	loc41 - location
	loc42 - location
	loc43 - location
	loc44 - location
	loc45 - location
	loc46 - location
	loc47 - location
	loc48 - location
	crate1 - crate
	crate2 - crate
	crate3 - crate
	crate4 - crate
	crate5 - crate
	crate6 - crate
	crate7 - crate
	crate8 - crate
	crate9 - crate
	crate10 - crate
	crate11 - crate
	crate12 - crate
	crate13 - crate
	crate14 - crate
	crate15 - crate
	crate16 - crate
	crate17 - crate
	crate18 - crate
	crate19 - crate
	crate20 - crate
	crate21 - crate
	crate22 - crate
	crate23 - crate
	crate24 - crate
	crate25 - crate
	crate26 - crate
	crate27 - crate
	crate28 - crate
	crate29 - crate
	crate30 - crate
	crate31 - crate
	crate32 - crate
	crate33 - crate
	crate34 - crate
	crate35 - crate
	crate36 - crate
	crate37 - crate
	crate38 - crate
	crate39 - crate
	crate40 - crate
	crate41 - crate
	crate42 - crate
	crate43 - crate
	crate44 - crate
	crate45 - crate
	crate46 - crate
	crate47 - crate
	crate48 - crate
	food - content
	medicine - content
	person1 - person
	person2 - person
	person3 - person
	person4 - person
	person5 - person
	person6 - person
	person7 - person
	person8 - person
	person9 - person
	person10 - person
	person11 - person
	person12 - person
	person13 - person
	person14 - person
	person15 - person
	person16 - person
	person17 - person
	person18 - person
	person19 - person
	person20 - person
	person21 - person
	person22 - person
	person23 - person
	person24 - person
	person25 - person
	person26 - person
	person27 - person
	person28 - person
	person29 - person
	person30 - person
	person31 - person
	person32 - person
	person33 - person
	person34 - person
	person35 - person
	person36 - person
	person37 - person
	person38 - person
	person39 - person
	person40 - person
	person41 - person
	person42 - person
	person43 - person
	person44 - person
	person45 - person
	person46 - person
	person47 - person
	person48 - person
	left right - arm
)
(:init
	(drone-at drone1 depot)
	(crate-at crate1 warehouse)
	(crate-at crate2 warehouse)
	(crate-at crate3 warehouse)
	(crate-at crate4 warehouse)
	(crate-at crate5 warehouse)
	(crate-at crate6 warehouse)
	(crate-at crate7 warehouse)
	(crate-at crate8 warehouse)
	(crate-at crate9 warehouse)
	(crate-at crate10 warehouse)
	(crate-at crate11 warehouse)
	(crate-at crate12 warehouse)
	(crate-at crate13 warehouse)
	(crate-at crate14 warehouse)
	(crate-at crate15 warehouse)
	(crate-at crate16 warehouse)
	(crate-at crate17 warehouse)
	(crate-at crate18 warehouse)
	(crate-at crate19 warehouse)
	(crate-at crate20 warehouse)
	(crate-at crate21 warehouse)
	(crate-at crate22 warehouse)
	(crate-at crate23 warehouse)
	(crate-at crate24 warehouse)
	(crate-at crate25 warehouse)
	(crate-at crate26 warehouse)
	(crate-at crate27 warehouse)
	(crate-at crate28 warehouse)
	(crate-at crate29 warehouse)
	(crate-at crate30 warehouse)
	(crate-at crate31 warehouse)
	(crate-at crate32 warehouse)
	(crate-at crate33 warehouse)
	(crate-at crate34 warehouse)
	(crate-at crate35 warehouse)
	(crate-at crate36 warehouse)
	(crate-at crate37 warehouse)
	(crate-at crate38 warehouse)
	(crate-at crate39 warehouse)
	(crate-at crate40 warehouse)
	(crate-at crate41 warehouse)
	(crate-at crate42 warehouse)
	(crate-at crate43 warehouse)
	(crate-at crate44 warehouse)
	(crate-at crate45 warehouse)
	(crate-at crate46 warehouse)
	(crate-at crate47 warehouse)
	(crate-at crate48 warehouse)
	(empty-arm drone1 left)
	(empty-arm drone1 right)
	(content-crate food crate1)
	(content-crate food crate2)
	(content-crate food crate3)
	(content-crate food crate4)
	(content-crate food crate5)
	(content-crate food crate6)
	(content-crate food crate7)
	(content-crate food crate8)
	(content-crate food crate9)
	(content-crate food crate10)
	(content-crate food crate11)
	(content-crate food crate12)
	(content-crate food crate13)
	(content-crate food crate14)
	(content-crate food crate15)
	(content-crate food crate16)
	(content-crate food crate17)
	(content-crate food crate18)
	(content-crate food crate19)
	(content-crate food crate20)
	(content-crate food crate21)
	(content-crate food crate22)
	(content-crate food crate23)
	(content-crate food crate24)
	(content-crate food crate25)
	(content-crate food crate26)
	(content-crate food crate27)
	(content-crate food crate28)
	(content-crate food crate29)
	(content-crate food crate30)
	(content-crate food crate31)
	(content-crate food crate32)
	(content-crate food crate33)
	(content-crate medicine crate34)
	(content-crate medicine crate35)
	(content-crate medicine crate36)
	(content-crate medicine crate37)
	(content-crate medicine crate38)
	(content-crate medicine crate39)
	(content-crate medicine crate40)
	(content-crate medicine crate41)
	(content-crate medicine crate42)
	(content-crate medicine crate43)
	(content-crate medicine crate44)
	(content-crate medicine crate45)
	(content-crate medicine crate46)
	(content-crate medicine crate47)
	(content-crate medicine crate48)
	(person-at person1 loc33)
	(person-at person2 loc21)
	(person-at person3 loc32)
	(person-at person4 loc24)
	(person-at person5 loc5)
	(person-at person6 loc14)
	(person-at person7 loc24)
	(person-at person8 loc28)
	(person-at person9 loc48)
	(person-at person10 loc4)
	(person-at person11 loc35)
	(person-at person12 loc44)
	(person-at person13 loc36)
	(person-at person14 loc21)
	(person-at person15 loc19)
	(person-at person16 loc38)
	(person-at person17 loc10)
	(person-at person18 loc32)
	(person-at person19 loc17)
	(person-at person20 loc39)
	(person-at person21 loc10)
	(person-at person22 loc47)
	(person-at person23 loc42)
	(person-at person24 loc19)
	(person-at person25 loc35)
	(person-at person26 loc36)
	(person-at person27 loc11)
	(person-at person28 loc17)
	(person-at person29 loc24)
	(person-at person30 loc16)
	(person-at person31 loc48)
	(person-at person32 loc8)
	(person-at person33 loc7)
	(person-at person34 loc31)
	(person-at person35 loc16)
	(person-at person36 loc37)
	(person-at person37 loc5)
	(person-at person38 loc16)
	(person-at person39 loc21)
	(person-at person40 loc14)
	(person-at person41 loc32)
	(person-at person42 loc11)
	(person-at person43 loc26)
	(person-at person44 loc13)
	(person-at person45 loc39)
	(person-at person46 loc37)
	(person-at person47 loc30)
	(person-at person48 loc34)
	(person-need person1 medicine)
	(person-need person2 food)
	(person-need person3 food)
	(person-need person3 medicine)
	(person-need person4 food)
	(person-need person4 medicine)
	(person-need person5 food)
	(person-need person6 food)
	(person-need person8 food)
	(person-need person9 food)
	(person-need person9 medicine)
	(person-need person10 medicine)
	(person-need person11 food)
	(person-need person12 food)
	(person-need person13 food)
	(person-need person14 food)
	(person-need person14 medicine)
	(person-need person15 food)
	(person-need person16 food)
	(person-need person17 food)
	(person-need person20 food)
	(person-need person21 food)
	(person-need person23 food)
	(person-need person24 food)
	(person-need person25 food)
	(person-need person25 medicine)
	(person-need person27 food)
	(person-need person31 medicine)
	(person-need person32 food)
	(person-need person33 food)
	(person-need person33 medicine)
	(person-need person34 food)
	(person-need person35 food)
	(person-need person36 medicine)
	(person-need person37 food)
	(person-need person38 food)
	(person-need person38 medicine)
	(person-need person39 medicine)
	(person-need person40 food)
	(person-need person40 medicine)
	(person-need person41 food)
	(person-need person42 food)
	(person-need person43 food)
	(person-need person46 food)
	(person-need person46 medicine)
	(person-need person47 food)
	(person-need person48 food)
	(person-need person48 medicine)
)
(:goal (and
	(drone-at drone1 depot)
	(has-content-person person1 medicine)
	(has-content-person person2 food)
	(has-content-person person3 food)
	(has-content-person person3 medicine)
	(has-content-person person4 food)
	(has-content-person person4 medicine)
	(has-content-person person5 food)
	(has-content-person person6 food)
	(has-content-person person8 food)
	(has-content-person person9 food)
	(has-content-person person9 medicine)
	(has-content-person person10 medicine)
	(has-content-person person11 food)
	(has-content-person person12 food)
	(has-content-person person13 food)
	(has-content-person person14 food)
	(has-content-person person14 medicine)
	(has-content-person person15 food)
	(has-content-person person16 food)
	(has-content-person person17 food)
	(has-content-person person20 food)
	(has-content-person person21 food)
	(has-content-person person23 food)
	(has-content-person person24 food)
	(has-content-person person25 food)
	(has-content-person person25 medicine)
	(has-content-person person27 food)
	(has-content-person person31 medicine)
	(has-content-person person32 food)
	(has-content-person person33 food)
	(has-content-person person33 medicine)
	(has-content-person person34 food)
	(has-content-person person35 food)
	(has-content-person person36 medicine)
	(has-content-person person37 food)
	(has-content-person person38 food)
	(has-content-person person38 medicine)
	(has-content-person person39 medicine)
	(has-content-person person40 food)
	(has-content-person person40 medicine)
	(has-content-person person41 food)
	(has-content-person person42 food)
	(has-content-person person43 food)
	(has-content-person person46 food)
	(has-content-person person46 medicine)
	(has-content-person person47 food)
	(has-content-person person48 food)
	(has-content-person person48 medicine)
))
)
