(define (problem drone_problem_d1_r0_l21_p21_c21_g21_ct2)
(:domain p1)
(:objects
	drone1 - drone
	depot - location
	loc1 - location
	loc2 - location
	loc3 - location
	loc4 - location
	loc5 - location
	loc6 - location
	loc7 - location
	loc8 - location
	loc9 - location
	loc10 - location
	loc11 - location
	loc12 - location
	loc13 - location
	loc14 - location
	loc15 - location
	loc16 - location
	loc17 - location
	loc18 - location
	loc19 - location
	loc20 - location
	loc21 - location
	crate1 - crate
	crate2 - crate
	crate3 - crate
	crate4 - crate
	crate5 - crate
	crate6 - crate
	crate7 - crate
	crate8 - crate
	crate9 - crate
	crate10 - crate
	crate11 - crate
	crate12 - crate
	crate13 - crate
	crate14 - crate
	crate15 - crate
	crate16 - crate
	crate17 - crate
	crate18 - crate
	crate19 - crate
	crate20 - crate
	crate21 - crate
	food - content
	medicine - content
	person1 - person
	person2 - person
	person3 - person
	person4 - person
	person5 - person
	person6 - person
	person7 - person
	person8 - person
	person9 - person
	person10 - person
	person11 - person
	person12 - person
	person13 - person
	person14 - person
	person15 - person
	person16 - person
	person17 - person
	person18 - person
	person19 - person
	person20 - person
	person21 - person
	left right - arm
)
(:init
	(drone-at drone1 depot)
	(crate-at crate1 depot)
	(crate-at crate2 depot)
	(crate-at crate3 depot)
	(crate-at crate4 depot)
	(crate-at crate5 depot)
	(crate-at crate6 depot)
	(crate-at crate7 depot)
	(crate-at crate8 depot)
	(crate-at crate9 depot)
	(crate-at crate10 depot)
	(crate-at crate11 depot)
	(crate-at crate12 depot)
	(crate-at crate13 depot)
	(crate-at crate14 depot)
	(crate-at crate15 depot)
	(crate-at crate16 depot)
	(crate-at crate17 depot)
	(crate-at crate18 depot)
	(crate-at crate19 depot)
	(crate-at crate20 depot)
	(crate-at crate21 depot)
	(empty-arm left)
	(empty-arm right)
	(content-crate food crate1)
	(content-crate food crate2)
	(content-crate medicine crate3)
	(content-crate medicine crate4)
	(content-crate medicine crate5)
	(content-crate medicine crate6)
	(content-crate medicine crate7)
	(content-crate medicine crate8)
	(content-crate medicine crate9)
	(content-crate medicine crate10)
	(content-crate medicine crate11)
	(content-crate medicine crate12)
	(content-crate medicine crate13)
	(content-crate medicine crate14)
	(content-crate medicine crate15)
	(content-crate medicine crate16)
	(content-crate medicine crate17)
	(content-crate medicine crate18)
	(content-crate medicine crate19)
	(content-crate medicine crate20)
	(content-crate medicine crate21)
	(person-at person1 loc18)
	(person-at person2 loc8)
	(person-at person3 loc18)
	(person-at person4 loc8)
	(person-at person5 loc1)
	(person-at person6 loc21)
	(person-at person7 loc12)
	(person-at person8 loc3)
	(person-at person9 loc16)
	(person-at person10 loc1)
	(person-at person11 loc6)
	(person-at person12 loc15)
	(person-at person13 loc15)
	(person-at person14 loc14)
	(person-at person15 loc13)
	(person-at person16 loc8)
	(person-at person17 loc3)
	(person-at person18 loc6)
	(person-at person19 loc14)
	(person-at person20 loc8)
	(person-at person21 loc8)
	(person-need person1 medicine)
	(person-need person2 food)
	(person-need person2 medicine)
	(person-need person3 medicine)
	(person-need person5 medicine)
	(person-need person6 medicine)
	(person-need person8 medicine)
	(person-need person9 food)
	(person-need person9 medicine)
	(person-need person10 medicine)
	(person-need person11 medicine)
	(person-need person12 medicine)
	(person-need person13 medicine)
	(person-need person14 medicine)
	(person-need person15 medicine)
	(person-need person16 medicine)
	(person-need person17 medicine)
	(person-need person18 medicine)
	(person-need person19 medicine)
	(person-need person20 medicine)
	(person-need person21 medicine)
)
(:goal (and
	(drone-at drone1 depot)
	(has-content-person person1 medicine)
	(has-content-person person2 food)
	(has-content-person person2 medicine)
	(has-content-person person3 medicine)
	(has-content-person person5 medicine)
	(has-content-person person6 medicine)
	(has-content-person person8 medicine)
	(has-content-person person9 food)
	(has-content-person person9 medicine)
	(has-content-person person10 medicine)
	(has-content-person person11 medicine)
	(has-content-person person12 medicine)
	(has-content-person person13 medicine)
	(has-content-person person14 medicine)
	(has-content-person person15 medicine)
	(has-content-person person16 medicine)
	(has-content-person person17 medicine)
	(has-content-person person18 medicine)
	(has-content-person person19 medicine)
	(has-content-person person20 medicine)
	(has-content-person person21 medicine)
))
)
