(define (problem drone_problem_d1_r0_l18_p18_c18_g18_ct2)
(:domain p1)
(:objects
	drone1 - drone
	depot - location
	warehouse - location
	loc1 - location
	loc2 - location
	loc3 - location
	loc4 - location
	loc5 - location
	loc6 - location
	loc7 - location
	loc8 - location
	loc9 - location
	loc10 - location
	loc11 - location
	loc12 - location
	loc13 - location
	loc14 - location
	loc15 - location
	loc16 - location
	loc17 - location
	loc18 - location
	crate1 - crate
	crate2 - crate
	crate3 - crate
	crate4 - crate
	crate5 - crate
	crate6 - crate
	crate7 - crate
	crate8 - crate
	crate9 - crate
	crate10 - crate
	crate11 - crate
	crate12 - crate
	crate13 - crate
	crate14 - crate
	crate15 - crate
	crate16 - crate
	crate17 - crate
	crate18 - crate
	food - content
	medicine - content
	person1 - person
	person2 - person
	person3 - person
	person4 - person
	person5 - person
	person6 - person
	person7 - person
	person8 - person
	person9 - person
	person10 - person
	person11 - person
	person12 - person
	person13 - person
	person14 - person
	person15 - person
	person16 - person
	person17 - person
	person18 - person
	left right - arm
)
(:init
	(drone-at drone1 depot)
	(crate-at crate1 warehouse)
	(crate-at crate2 warehouse)
	(crate-at crate3 warehouse)
	(crate-at crate4 warehouse)
	(crate-at crate5 warehouse)
	(crate-at crate6 warehouse)
	(crate-at crate7 warehouse)
	(crate-at crate8 warehouse)
	(crate-at crate9 warehouse)
	(crate-at crate10 warehouse)
	(crate-at crate11 warehouse)
	(crate-at crate12 warehouse)
	(crate-at crate13 warehouse)
	(crate-at crate14 warehouse)
	(crate-at crate15 warehouse)
	(crate-at crate16 warehouse)
	(crate-at crate17 warehouse)
	(crate-at crate18 warehouse)
	(empty-arm drone1 left)
	(empty-arm drone1 right)
	(content-crate food crate1)
	(content-crate food crate2)
	(content-crate food crate3)
	(content-crate food crate4)
	(content-crate food crate5)
	(content-crate food crate6)
	(content-crate food crate7)
	(content-crate medicine crate8)
	(content-crate medicine crate9)
	(content-crate medicine crate10)
	(content-crate medicine crate11)
	(content-crate medicine crate12)
	(content-crate medicine crate13)
	(content-crate medicine crate14)
	(content-crate medicine crate15)
	(content-crate medicine crate16)
	(content-crate medicine crate17)
	(content-crate medicine crate18)
	(person-at person1 loc16)
	(person-at person2 loc16)
	(person-at person3 loc10)
	(person-at person4 loc2)
	(person-at person5 loc18)
	(person-at person6 loc18)
	(person-at person7 loc16)
	(person-at person8 loc8)
	(person-at person9 loc10)
	(person-at person10 loc1)
	(person-at person11 loc2)
	(person-at person12 loc11)
	(person-at person13 loc13)
	(person-at person14 loc2)
	(person-at person15 loc4)
	(person-at person16 loc15)
	(person-at person17 loc10)
	(person-at person18 loc5)
	(person-need person2 medicine)
	(person-need person4 medicine)
	(person-need person5 medicine)
	(person-need person6 food)
	(person-need person7 medicine)
	(person-need person8 food)
	(person-need person9 food)
	(person-need person9 medicine)
	(person-need person10 medicine)
	(person-need person11 food)
	(person-need person11 medicine)
	(person-need person14 food)
	(person-need person14 medicine)
	(person-need person15 food)
	(person-need person15 medicine)
	(person-need person16 medicine)
	(person-need person17 food)
	(person-need person17 medicine)
)
(:goal (and
	(drone-at drone1 depot)
	(has-content-person person2 medicine)
	(has-content-person person4 medicine)
	(has-content-person person5 medicine)
	(has-content-person person6 food)
	(has-content-person person7 medicine)
	(has-content-person person8 food)
	(has-content-person person9 food)
	(has-content-person person9 medicine)
	(has-content-person person10 medicine)
	(has-content-person person11 food)
	(has-content-person person11 medicine)
	(has-content-person person14 food)
	(has-content-person person14 medicine)
	(has-content-person person15 food)
	(has-content-person person15 medicine)
	(has-content-person person16 medicine)
	(has-content-person person17 food)
	(has-content-person person17 medicine)
))
)
