(define (problem drone_problem_d1_r0_l42_p42_c42_g42_ct2)
(:domain p1)
(:objects
	drone1 - drone
	depot - location
	warehouse - location
	loc1 - location
	loc2 - location
	loc3 - location
	loc4 - location
	loc5 - location
	loc6 - location
	loc7 - location
	loc8 - location
	loc9 - location
	loc10 - location
	loc11 - location
	loc12 - location
	loc13 - location
	loc14 - location
	loc15 - location
	loc16 - location
	loc17 - location
	loc18 - location
	loc19 - location
	loc20 - location
	loc21 - location
	loc22 - location
	loc23 - location
	loc24 - location
	loc25 - location
	loc26 - location
	loc27 - location
	loc28 - location
	loc29 - location
	loc30 - location
	loc31 - location
	loc32 - location
	loc33 - location
	loc34 - location
	loc35 - location
	loc36 - location
	loc37 - location
	loc38 - location
	loc39 - location
	loc40 - location
	loc41 - location
	loc42 - location
	crate1 - crate
	crate2 - crate
	crate3 - crate
	crate4 - crate
	crate5 - crate
	crate6 - crate
	crate7 - crate
	crate8 - crate
	crate9 - crate
	crate10 - crate
	crate11 - crate
	crate12 - crate
	crate13 - crate
	crate14 - crate
	crate15 - crate
	crate16 - crate
	crate17 - crate
	crate18 - crate
	crate19 - crate
	crate20 - crate
	crate21 - crate
	crate22 - crate
	crate23 - crate
	crate24 - crate
	crate25 - crate
	crate26 - crate
	crate27 - crate
	crate28 - crate
	crate29 - crate
	crate30 - crate
	crate31 - crate
	crate32 - crate
	crate33 - crate
	crate34 - crate
	crate35 - crate
	crate36 - crate
	crate37 - crate
	crate38 - crate
	crate39 - crate
	crate40 - crate
	crate41 - crate
	crate42 - crate
	food - content
	medicine - content
	person1 - person
	person2 - person
	person3 - person
	person4 - person
	person5 - person
	person6 - person
	person7 - person
	person8 - person
	person9 - person
	person10 - person
	person11 - person
	person12 - person
	person13 - person
	person14 - person
	person15 - person
	person16 - person
	person17 - person
	person18 - person
	person19 - person
	person20 - person
	person21 - person
	person22 - person
	person23 - person
	person24 - person
	person25 - person
	person26 - person
	person27 - person
	person28 - person
	person29 - person
	person30 - person
	person31 - person
	person32 - person
	person33 - person
	person34 - person
	person35 - person
	person36 - person
	person37 - person
	person38 - person
	person39 - person
	person40 - person
	person41 - person
	person42 - person
	left right - arm
)
(:init
	(drone-at drone1 depot)
	(crate-at crate1 warehouse)
	(crate-at crate2 warehouse)
	(crate-at crate3 warehouse)
	(crate-at crate4 warehouse)
	(crate-at crate5 warehouse)
	(crate-at crate6 warehouse)
	(crate-at crate7 warehouse)
	(crate-at crate8 warehouse)
	(crate-at crate9 warehouse)
	(crate-at crate10 warehouse)
	(crate-at crate11 warehouse)
	(crate-at crate12 warehouse)
	(crate-at crate13 warehouse)
	(crate-at crate14 warehouse)
	(crate-at crate15 warehouse)
	(crate-at crate16 warehouse)
	(crate-at crate17 warehouse)
	(crate-at crate18 warehouse)
	(crate-at crate19 warehouse)
	(crate-at crate20 warehouse)
	(crate-at crate21 warehouse)
	(crate-at crate22 warehouse)
	(crate-at crate23 warehouse)
	(crate-at crate24 warehouse)
	(crate-at crate25 warehouse)
	(crate-at crate26 warehouse)
	(crate-at crate27 warehouse)
	(crate-at crate28 warehouse)
	(crate-at crate29 warehouse)
	(crate-at crate30 warehouse)
	(crate-at crate31 warehouse)
	(crate-at crate32 warehouse)
	(crate-at crate33 warehouse)
	(crate-at crate34 warehouse)
	(crate-at crate35 warehouse)
	(crate-at crate36 warehouse)
	(crate-at crate37 warehouse)
	(crate-at crate38 warehouse)
	(crate-at crate39 warehouse)
	(crate-at crate40 warehouse)
	(crate-at crate41 warehouse)
	(crate-at crate42 warehouse)
	(empty-arm drone1 left)
	(empty-arm drone1 right)
	(content-crate food crate1)
	(content-crate food crate2)
	(content-crate food crate3)
	(content-crate food crate4)
	(content-crate food crate5)
	(content-crate food crate6)
	(content-crate food crate7)
	(content-crate food crate8)
	(content-crate food crate9)
	(content-crate food crate10)
	(content-crate food crate11)
	(content-crate food crate12)
	(content-crate medicine crate13)
	(content-crate medicine crate14)
	(content-crate medicine crate15)
	(content-crate medicine crate16)
	(content-crate medicine crate17)
	(content-crate medicine crate18)
	(content-crate medicine crate19)
	(content-crate medicine crate20)
	(content-crate medicine crate21)
	(content-crate medicine crate22)
	(content-crate medicine crate23)
	(content-crate medicine crate24)
	(content-crate medicine crate25)
	(content-crate medicine crate26)
	(content-crate medicine crate27)
	(content-crate medicine crate28)
	(content-crate medicine crate29)
	(content-crate medicine crate30)
	(content-crate medicine crate31)
	(content-crate medicine crate32)
	(content-crate medicine crate33)
	(content-crate medicine crate34)
	(content-crate medicine crate35)
	(content-crate medicine crate36)
	(content-crate medicine crate37)
	(content-crate medicine crate38)
	(content-crate medicine crate39)
	(content-crate medicine crate40)
	(content-crate medicine crate41)
	(content-crate medicine crate42)
	(person-at person1 loc18)
	(person-at person2 loc10)
	(person-at person3 loc32)
	(person-at person4 loc8)
	(person-at person5 loc6)
	(person-at person6 loc34)
	(person-at person7 loc18)
	(person-at person8 loc27)
	(person-at person9 loc11)
	(person-at person10 loc2)
	(person-at person11 loc37)
	(person-at person12 loc38)
	(person-at person13 loc25)
	(person-at person14 loc24)
	(person-at person15 loc12)
	(person-at person16 loc11)
	(person-at person17 loc5)
	(person-at person18 loc5)
	(person-at person19 loc16)
	(person-at person20 loc31)
	(person-at person21 loc39)
	(person-at person22 loc38)
	(person-at person23 loc17)
	(person-at person24 loc32)
	(person-at person25 loc11)
	(person-at person26 loc15)
	(person-at person27 loc36)
	(person-at person28 loc39)
	(person-at person29 loc36)
	(person-at person30 loc18)
	(person-at person31 loc32)
	(person-at person32 loc30)
	(person-at person33 loc31)
	(person-at person34 loc28)
	(person-at person35 loc16)
	(person-at person36 loc10)
	(person-at person37 loc29)
	(person-at person38 loc23)
	(person-at person39 loc30)
	(person-at person40 loc27)
	(person-at person41 loc19)
	(person-at person42 loc26)
	(person-need person2 food)
	(person-need person2 medicine)
	(person-need person3 food)
	(person-need person4 medicine)
	(person-need person5 medicine)
	(person-need person6 food)
	(person-need person7 food)
	(person-need person8 medicine)
	(person-need person9 medicine)
	(person-need person10 food)
	(person-need person11 medicine)
	(person-need person12 medicine)
	(person-need person13 medicine)
	(person-need person14 food)
	(person-need person14 medicine)
	(person-need person15 medicine)
	(person-need person17 food)
	(person-need person17 medicine)
	(person-need person18 medicine)
	(person-need person19 food)
	(person-need person20 medicine)
	(person-need person21 medicine)
	(person-need person22 medicine)
	(person-need person23 medicine)
	(person-need person24 medicine)
	(person-need person26 food)
	(person-need person26 medicine)
	(person-need person27 food)
	(person-need person27 medicine)
	(person-need person29 medicine)
	(person-need person30 medicine)
	(person-need person31 medicine)
	(person-need person32 medicine)
	(person-need person33 food)
	(person-need person33 medicine)
	(person-need person34 food)
	(person-need person35 medicine)
	(person-need person36 medicine)
	(person-need person39 medicine)
	(person-need person40 medicine)
	(person-need person41 medicine)
	(person-need person42 medicine)
)
(:goal (and
	(drone-at drone1 depot)
	(has-content-person person2 food)
	(has-content-person person2 medicine)
	(has-content-person person3 food)
	(has-content-person person4 medicine)
	(has-content-person person5 medicine)
	(has-content-person person6 food)
	(has-content-person person7 food)
	(has-content-person person8 medicine)
	(has-content-person person9 medicine)
	(has-content-person person10 food)
	(has-content-person person11 medicine)
	(has-content-person person12 medicine)
	(has-content-person person13 medicine)
	(has-content-person person14 food)
	(has-content-person person14 medicine)
	(has-content-person person15 medicine)
	(has-content-person person17 food)
	(has-content-person person17 medicine)
	(has-content-person person18 medicine)
	(has-content-person person19 food)
	(has-content-person person20 medicine)
	(has-content-person person21 medicine)
	(has-content-person person22 medicine)
	(has-content-person person23 medicine)
	(has-content-person person24 medicine)
	(has-content-person person26 food)
	(has-content-person person26 medicine)
	(has-content-person person27 food)
	(has-content-person person27 medicine)
	(has-content-person person29 medicine)
	(has-content-person person30 medicine)
	(has-content-person person31 medicine)
	(has-content-person person32 medicine)
	(has-content-person person33 food)
	(has-content-person person33 medicine)
	(has-content-person person34 food)
	(has-content-person person35 medicine)
	(has-content-person person36 medicine)
	(has-content-person person39 medicine)
	(has-content-person person40 medicine)
	(has-content-person person41 medicine)
	(has-content-person person42 medicine)
))
)
