(define (problem drone_problem_d1_r0_l13_p13_c13_g13_ct2)
(:domain p1)
(:objects
	drone1 - drone
	depot - location
	loc1 - location
	loc2 - location
	loc3 - location
	loc4 - location
	loc5 - location
	loc6 - location
	loc7 - location
	loc8 - location
	loc9 - location
	loc10 - location
	loc11 - location
	loc12 - location
	loc13 - location
	crate1 - crate
	crate2 - crate
	crate3 - crate
	crate4 - crate
	crate5 - crate
	crate6 - crate
	crate7 - crate
	crate8 - crate
	crate9 - crate
	crate10 - crate
	crate11 - crate
	crate12 - crate
	crate13 - crate
	food - content
	medicine - content
	person1 - person
	person2 - person
	person3 - person
	person4 - person
	person5 - person
	person6 - person
	person7 - person
	person8 - person
	person9 - person
	person10 - person
	person11 - person
	person12 - person
	person13 - person
	left right - arm
)
(:init
	(drone-at drone1 depot)
	(crate-at crate1 depot)
	(crate-at crate2 depot)
	(crate-at crate3 depot)
	(crate-at crate4 depot)
	(crate-at crate5 depot)
	(crate-at crate6 depot)
	(crate-at crate7 depot)
	(crate-at crate8 depot)
	(crate-at crate9 depot)
	(crate-at crate10 depot)
	(crate-at crate11 depot)
	(crate-at crate12 depot)
	(crate-at crate13 depot)
	(empty-arm left)
	(empty-arm right)
	(content-crate food crate1)
	(content-crate food crate2)
	(content-crate food crate3)
	(content-crate medicine crate4)
	(content-crate medicine crate5)
	(content-crate medicine crate6)
	(content-crate medicine crate7)
	(content-crate medicine crate8)
	(content-crate medicine crate9)
	(content-crate medicine crate10)
	(content-crate medicine crate11)
	(content-crate medicine crate12)
	(content-crate medicine crate13)
	(person-at person1 loc12)
	(person-at person2 loc3)
	(person-at person3 loc9)
	(person-at person4 loc5)
	(person-at person5 loc8)
	(person-at person6 loc11)
	(person-at person7 loc3)
	(person-at person8 loc11)
	(person-at person9 loc6)
	(person-at person10 loc2)
	(person-at person11 loc2)
	(person-at person12 loc3)
	(person-at person13 loc8)
	(person-need person1 medicine)
	(person-need person2 medicine)
	(person-need person3 food)
	(person-need person4 medicine)
	(person-need person6 medicine)
	(person-need person7 medicine)
	(person-need person9 medicine)
	(person-need person10 medicine)
	(person-need person11 food)
	(person-need person11 medicine)
	(person-need person12 food)
	(person-need person12 medicine)
	(person-need person13 medicine)
)
(:goal (and
	(drone-at drone1 depot)
	(has-content-person person1 medicine)
	(has-content-person person2 medicine)
	(has-content-person person3 food)
	(has-content-person person4 medicine)
	(has-content-person person6 medicine)
	(has-content-person person7 medicine)
	(has-content-person person9 medicine)
	(has-content-person person10 medicine)
	(has-content-person person11 food)
	(has-content-person person11 medicine)
	(has-content-person person12 food)
	(has-content-person person12 medicine)
	(has-content-person person13 medicine)
))
)
