(define (problem drone_problem_d1_r1_l90_p90_c90_g90_ct2)
(:domain p2)
(:objects
	drone1 - drone
	depot - location
	loc1 - location
	loc2 - location
	loc3 - location
	loc4 - location
	loc5 - location
	loc6 - location
	loc7 - location
	loc8 - location
	loc9 - location
	loc10 - location
	loc11 - location
	loc12 - location
	loc13 - location
	loc14 - location
	loc15 - location
	loc16 - location
	loc17 - location
	loc18 - location
	loc19 - location
	loc20 - location
	loc21 - location
	loc22 - location
	loc23 - location
	loc24 - location
	loc25 - location
	loc26 - location
	loc27 - location
	loc28 - location
	loc29 - location
	loc30 - location
	loc31 - location
	loc32 - location
	loc33 - location
	loc34 - location
	loc35 - location
	loc36 - location
	loc37 - location
	loc38 - location
	loc39 - location
	loc40 - location
	loc41 - location
	loc42 - location
	loc43 - location
	loc44 - location
	loc45 - location
	loc46 - location
	loc47 - location
	loc48 - location
	loc49 - location
	loc50 - location
	loc51 - location
	loc52 - location
	loc53 - location
	loc54 - location
	loc55 - location
	loc56 - location
	loc57 - location
	loc58 - location
	loc59 - location
	loc60 - location
	loc61 - location
	loc62 - location
	loc63 - location
	loc64 - location
	loc65 - location
	loc66 - location
	loc67 - location
	loc68 - location
	loc69 - location
	loc70 - location
	loc71 - location
	loc72 - location
	loc73 - location
	loc74 - location
	loc75 - location
	loc76 - location
	loc77 - location
	loc78 - location
	loc79 - location
	loc80 - location
	loc81 - location
	loc82 - location
	loc83 - location
	loc84 - location
	loc85 - location
	loc86 - location
	loc87 - location
	loc88 - location
	loc89 - location
	loc90 - location
	crate1 - crate
	crate2 - crate
	crate3 - crate
	crate4 - crate
	crate5 - crate
	crate6 - crate
	crate7 - crate
	crate8 - crate
	crate9 - crate
	crate10 - crate
	crate11 - crate
	crate12 - crate
	crate13 - crate
	crate14 - crate
	crate15 - crate
	crate16 - crate
	crate17 - crate
	crate18 - crate
	crate19 - crate
	crate20 - crate
	crate21 - crate
	crate22 - crate
	crate23 - crate
	crate24 - crate
	crate25 - crate
	crate26 - crate
	crate27 - crate
	crate28 - crate
	crate29 - crate
	crate30 - crate
	crate31 - crate
	crate32 - crate
	crate33 - crate
	crate34 - crate
	crate35 - crate
	crate36 - crate
	crate37 - crate
	crate38 - crate
	crate39 - crate
	crate40 - crate
	crate41 - crate
	crate42 - crate
	crate43 - crate
	crate44 - crate
	crate45 - crate
	crate46 - crate
	crate47 - crate
	crate48 - crate
	crate49 - crate
	crate50 - crate
	crate51 - crate
	crate52 - crate
	crate53 - crate
	crate54 - crate
	crate55 - crate
	crate56 - crate
	crate57 - crate
	crate58 - crate
	crate59 - crate
	crate60 - crate
	crate61 - crate
	crate62 - crate
	crate63 - crate
	crate64 - crate
	crate65 - crate
	crate66 - crate
	crate67 - crate
	crate68 - crate
	crate69 - crate
	crate70 - crate
	crate71 - crate
	crate72 - crate
	crate73 - crate
	crate74 - crate
	crate75 - crate
	crate76 - crate
	crate77 - crate
	crate78 - crate
	crate79 - crate
	crate80 - crate
	crate81 - crate
	crate82 - crate
	crate83 - crate
	crate84 - crate
	crate85 - crate
	crate86 - crate
	crate87 - crate
	crate88 - crate
	crate89 - crate
	crate90 - crate
	food - content
	medicine - content
	person1 - person
	person2 - person
	person3 - person
	person4 - person
	person5 - person
	person6 - person
	person7 - person
	person8 - person
	person9 - person
	person10 - person
	person11 - person
	person12 - person
	person13 - person
	person14 - person
	person15 - person
	person16 - person
	person17 - person
	person18 - person
	person19 - person
	person20 - person
	person21 - person
	person22 - person
	person23 - person
	person24 - person
	person25 - person
	person26 - person
	person27 - person
	person28 - person
	person29 - person
	person30 - person
	person31 - person
	person32 - person
	person33 - person
	person34 - person
	person35 - person
	person36 - person
	person37 - person
	person38 - person
	person39 - person
	person40 - person
	person41 - person
	person42 - person
	person43 - person
	person44 - person
	person45 - person
	person46 - person
	person47 - person
	person48 - person
	person49 - person
	person50 - person
	person51 - person
	person52 - person
	person53 - person
	person54 - person
	person55 - person
	person56 - person
	person57 - person
	person58 - person
	person59 - person
	person60 - person
	person61 - person
	person62 - person
	person63 - person
	person64 - person
	person65 - person
	person66 - person
	person67 - person
	person68 - person
	person69 - person
	person70 - person
	person71 - person
	person72 - person
	person73 - person
	person74 - person
	person75 - person
	person76 - person
	person77 - person
	person78 - person
	person79 - person
	person80 - person
	person81 - person
	person82 - person
	person83 - person
	person84 - person
	person85 - person
	person86 - person
	person87 - person
	person88 - person
	person89 - person
	person90 - person
	carrier1 - carrier
	N0 - num
	N1 - num
	N2 - num
	N3 - num
	N4 - num
	N5 - num
	N6 - num
	N7 - num
)
(:init
	(drone-at drone1 depot)
	(crate-at crate1 depot)
	(crate-at crate2 depot)
	(crate-at crate3 depot)
	(crate-at crate4 depot)
	(crate-at crate5 depot)
	(crate-at crate6 depot)
	(crate-at crate7 depot)
	(crate-at crate8 depot)
	(crate-at crate9 depot)
	(crate-at crate10 depot)
	(crate-at crate11 depot)
	(crate-at crate12 depot)
	(crate-at crate13 depot)
	(crate-at crate14 depot)
	(crate-at crate15 depot)
	(crate-at crate16 depot)
	(crate-at crate17 depot)
	(crate-at crate18 depot)
	(crate-at crate19 depot)
	(crate-at crate20 depot)
	(crate-at crate21 depot)
	(crate-at crate22 depot)
	(crate-at crate23 depot)
	(crate-at crate24 depot)
	(crate-at crate25 depot)
	(crate-at crate26 depot)
	(crate-at crate27 depot)
	(crate-at crate28 depot)
	(crate-at crate29 depot)
	(crate-at crate30 depot)
	(crate-at crate31 depot)
	(crate-at crate32 depot)
	(crate-at crate33 depot)
	(crate-at crate34 depot)
	(crate-at crate35 depot)
	(crate-at crate36 depot)
	(crate-at crate37 depot)
	(crate-at crate38 depot)
	(crate-at crate39 depot)
	(crate-at crate40 depot)
	(crate-at crate41 depot)
	(crate-at crate42 depot)
	(crate-at crate43 depot)
	(crate-at crate44 depot)
	(crate-at crate45 depot)
	(crate-at crate46 depot)
	(crate-at crate47 depot)
	(crate-at crate48 depot)
	(crate-at crate49 depot)
	(crate-at crate50 depot)
	(crate-at crate51 depot)
	(crate-at crate52 depot)
	(crate-at crate53 depot)
	(crate-at crate54 depot)
	(crate-at crate55 depot)
	(crate-at crate56 depot)
	(crate-at crate57 depot)
	(crate-at crate58 depot)
	(crate-at crate59 depot)
	(crate-at crate60 depot)
	(crate-at crate61 depot)
	(crate-at crate62 depot)
	(crate-at crate63 depot)
	(crate-at crate64 depot)
	(crate-at crate65 depot)
	(crate-at crate66 depot)
	(crate-at crate67 depot)
	(crate-at crate68 depot)
	(crate-at crate69 depot)
	(crate-at crate70 depot)
	(crate-at crate71 depot)
	(crate-at crate72 depot)
	(crate-at crate73 depot)
	(crate-at crate74 depot)
	(crate-at crate75 depot)
	(crate-at crate76 depot)
	(crate-at crate77 depot)
	(crate-at crate78 depot)
	(crate-at crate79 depot)
	(crate-at crate80 depot)
	(crate-at crate81 depot)
	(crate-at crate82 depot)
	(crate-at crate83 depot)
	(crate-at crate84 depot)
	(crate-at crate85 depot)
	(crate-at crate86 depot)
	(crate-at crate87 depot)
	(crate-at crate88 depot)
	(crate-at crate89 depot)
	(crate-at crate90 depot)
	(carrier-at carrier1 depot)
	(carrier-capacity carrier1 N4)
	(crates-in-carrier carrier1 N0)
	(content-crate food crate1)
	(content-crate food crate2)
	(content-crate food crate3)
	(content-crate food crate4)
	(content-crate food crate5)
	(content-crate food crate6)
	(content-crate food crate7)
	(content-crate food crate8)
	(content-crate food crate9)
	(content-crate food crate10)
	(content-crate food crate11)
	(content-crate food crate12)
	(content-crate food crate13)
	(content-crate food crate14)
	(content-crate food crate15)
	(content-crate food crate16)
	(content-crate food crate17)
	(content-crate food crate18)
	(content-crate food crate19)
	(content-crate food crate20)
	(content-crate food crate21)
	(content-crate food crate22)
	(content-crate food crate23)
	(content-crate food crate24)
	(content-crate food crate25)
	(content-crate food crate26)
	(content-crate food crate27)
	(content-crate food crate28)
	(content-crate food crate29)
	(content-crate food crate30)
	(content-crate food crate31)
	(content-crate food crate32)
	(content-crate food crate33)
	(content-crate food crate34)
	(content-crate food crate35)
	(content-crate food crate36)
	(content-crate food crate37)
	(content-crate food crate38)
	(content-crate food crate39)
	(content-crate food crate40)
	(content-crate food crate41)
	(content-crate food crate42)
	(content-crate food crate43)
	(content-crate food crate44)
	(content-crate food crate45)
	(content-crate food crate46)
	(content-crate food crate47)
	(content-crate food crate48)
	(content-crate food crate49)
	(content-crate food crate50)
	(content-crate medicine crate51)
	(content-crate medicine crate52)
	(content-crate medicine crate53)
	(content-crate medicine crate54)
	(content-crate medicine crate55)
	(content-crate medicine crate56)
	(content-crate medicine crate57)
	(content-crate medicine crate58)
	(content-crate medicine crate59)
	(content-crate medicine crate60)
	(content-crate medicine crate61)
	(content-crate medicine crate62)
	(content-crate medicine crate63)
	(content-crate medicine crate64)
	(content-crate medicine crate65)
	(content-crate medicine crate66)
	(content-crate medicine crate67)
	(content-crate medicine crate68)
	(content-crate medicine crate69)
	(content-crate medicine crate70)
	(content-crate medicine crate71)
	(content-crate medicine crate72)
	(content-crate medicine crate73)
	(content-crate medicine crate74)
	(content-crate medicine crate75)
	(content-crate medicine crate76)
	(content-crate medicine crate77)
	(content-crate medicine crate78)
	(content-crate medicine crate79)
	(content-crate medicine crate80)
	(content-crate medicine crate81)
	(content-crate medicine crate82)
	(content-crate medicine crate83)
	(content-crate medicine crate84)
	(content-crate medicine crate85)
	(content-crate medicine crate86)
	(content-crate medicine crate87)
	(content-crate medicine crate88)
	(content-crate medicine crate89)
	(content-crate medicine crate90)
	(person-at person1 loc59)
	(person-at person2 loc49)
	(person-at person3 loc47)
	(person-at person4 loc70)
	(person-at person5 loc20)
	(person-at person6 loc14)
	(person-at person7 loc77)
	(person-at person8 loc63)
	(person-at person9 loc19)
	(person-at person10 loc73)
	(person-at person11 loc52)
	(person-at person12 loc82)
	(person-at person13 loc88)
	(person-at person14 loc55)
	(person-at person15 loc67)
	(person-at person16 loc64)
	(person-at person17 loc87)
	(person-at person18 loc42)
	(person-at person19 loc64)
	(person-at person20 loc64)
	(person-at person21 loc82)
	(person-at person22 loc86)
	(person-at person23 loc26)
	(person-at person24 loc70)
	(person-at person25 loc79)
	(person-at person26 loc29)
	(person-at person27 loc2)
	(person-at person28 loc44)
	(person-at person29 loc41)
	(person-at person30 loc42)
	(person-at person31 loc5)
	(person-at person32 loc68)
	(person-at person33 loc19)
	(person-at person34 loc33)
	(person-at person35 loc78)
	(person-at person36 loc20)
	(person-at person37 loc49)
	(person-at person38 loc75)
	(person-at person39 loc38)
	(person-at person40 loc61)
	(person-at person41 loc9)
	(person-at person42 loc11)
	(person-at person43 loc67)
	(person-at person44 loc6)
	(person-at person45 loc9)
	(person-at person46 loc29)
	(person-at person47 loc17)
	(person-at person48 loc6)
	(person-at person49 loc39)
	(person-at person50 loc2)
	(person-at person51 loc58)
	(person-at person52 loc43)
	(person-at person53 loc21)
	(person-at person54 loc20)
	(person-at person55 loc84)
	(person-at person56 loc59)
	(person-at person57 loc48)
	(person-at person58 loc65)
	(person-at person59 loc49)
	(person-at person60 loc68)
	(person-at person61 loc65)
	(person-at person62 loc5)
	(person-at person63 loc74)
	(person-at person64 loc12)
	(person-at person65 loc87)
	(person-at person66 loc67)
	(person-at person67 loc77)
	(person-at person68 loc10)
	(person-at person69 loc55)
	(person-at person70 loc27)
	(person-at person71 loc38)
	(person-at person72 loc69)
	(person-at person73 loc77)
	(person-at person74 loc54)
	(person-at person75 loc62)
	(person-at person76 loc50)
	(person-at person77 loc78)
	(person-at person78 loc76)
	(person-at person79 loc30)
	(person-at person80 loc3)
	(person-at person81 loc85)
	(person-at person82 loc1)
	(person-at person83 loc24)
	(person-at person84 loc39)
	(person-at person85 loc65)
	(person-at person86 loc73)
	(person-at person87 loc33)
	(person-at person88 loc43)
	(person-at person89 loc9)
	(person-at person90 loc64)
	(next-num N0 N1)
	(next-num N1 N2)
	(next-num N2 N3)
	(next-num N3 N4)
	(next-num N4 N5)
	(next-num N5 N6)
	(next-num N6 N7)
)
(:goal (and
	(drone-at drone1 depot)
	(has-content-person person1 food)
	(has-content-person person2 food)
	(has-content-person person2 medicine)
	(has-content-person person3 medicine)
	(has-content-person person5 medicine)
	(has-content-person person6 food)
	(has-content-person person6 medicine)
	(has-content-person person7 medicine)
	(has-content-person person8 food)
	(has-content-person person9 food)
	(has-content-person person9 medicine)
	(has-content-person person13 medicine)
	(has-content-person person14 food)
	(has-content-person person15 food)
	(has-content-person person16 medicine)
	(has-content-person person17 food)
	(has-content-person person18 food)
	(has-content-person person20 food)
	(has-content-person person20 medicine)
	(has-content-person person21 food)
	(has-content-person person21 medicine)
	(has-content-person person22 medicine)
	(has-content-person person23 food)
	(has-content-person person24 food)
	(has-content-person person25 food)
	(has-content-person person26 food)
	(has-content-person person26 medicine)
	(has-content-person person27 food)
	(has-content-person person27 medicine)
	(has-content-person person28 food)
	(has-content-person person29 food)
	(has-content-person person29 medicine)
	(has-content-person person33 food)
	(has-content-person person34 food)
	(has-content-person person36 food)
	(has-content-person person38 food)
	(has-content-person person39 medicine)
	(has-content-person person40 medicine)
	(has-content-person person41 food)
	(has-content-person person42 medicine)
	(has-content-person person43 food)
	(has-content-person person43 medicine)
	(has-content-person person44 food)
	(has-content-person person45 medicine)
	(has-content-person person46 food)
	(has-content-person person46 medicine)
	(has-content-person person47 food)
	(has-content-person person47 medicine)
	(has-content-person person48 food)
	(has-content-person person49 medicine)
	(has-content-person person50 medicine)
	(has-content-person person51 food)
	(has-content-person person52 medicine)
	(has-content-person person54 food)
	(has-content-person person55 food)
	(has-content-person person56 food)
	(has-content-person person58 food)
	(has-content-person person58 medicine)
	(has-content-person person59 food)
	(has-content-person person60 food)
	(has-content-person person62 food)
	(has-content-person person62 medicine)
	(has-content-person person65 medicine)
	(has-content-person person68 medicine)
	(has-content-person person70 medicine)
	(has-content-person person71 food)
	(has-content-person person72 food)
	(has-content-person person72 medicine)
	(has-content-person person73 food)
	(has-content-person person73 medicine)
	(has-content-person person75 food)
	(has-content-person person75 medicine)
	(has-content-person person76 food)
	(has-content-person person76 medicine)
	(has-content-person person78 food)
	(has-content-person person79 medicine)
	(has-content-person person80 food)
	(has-content-person person82 food)
	(has-content-person person82 medicine)
	(has-content-person person83 medicine)
	(has-content-person person84 medicine)
	(has-content-person person85 food)
	(has-content-person person86 food)
	(has-content-person person87 food)
	(has-content-person person87 medicine)
	(has-content-person person88 food)
	(has-content-person person88 medicine)
	(has-content-person person89 food)
	(has-content-person person90 food)
	(has-content-person person90 medicine)
))
)
