(define (problem drone_problem_d1_r1_l18_p18_c18_g18_ct2)
(:domain p2)
(:objects
	drone1 - drone
	depot - location
	loc1 - location
	loc2 - location
	loc3 - location
	loc4 - location
	loc5 - location
	loc6 - location
	loc7 - location
	loc8 - location
	loc9 - location
	loc10 - location
	loc11 - location
	loc12 - location
	loc13 - location
	loc14 - location
	loc15 - location
	loc16 - location
	loc17 - location
	loc18 - location
	crate1 - crate
	crate2 - crate
	crate3 - crate
	crate4 - crate
	crate5 - crate
	crate6 - crate
	crate7 - crate
	crate8 - crate
	crate9 - crate
	crate10 - crate
	crate11 - crate
	crate12 - crate
	crate13 - crate
	crate14 - crate
	crate15 - crate
	crate16 - crate
	crate17 - crate
	crate18 - crate
	food - content
	medicine - content
	person1 - person
	person2 - person
	person3 - person
	person4 - person
	person5 - person
	person6 - person
	person7 - person
	person8 - person
	person9 - person
	person10 - person
	person11 - person
	person12 - person
	person13 - person
	person14 - person
	person15 - person
	person16 - person
	person17 - person
	person18 - person
	carrier1 - carrier
	space1 - carrier_space
	space2 - carrier_space
	space3 - carrier_space
	space4 - carrier_space
	N0 - num
	N1 - num
	N2 - num
	N3 - num
	N4 - num
	N5 - num
	N6 - num
	N7 - num
)
(:init
	(drone-at drone1 depot)
	(crate-at crate1 depot)
	(crate-at crate2 depot)
	(crate-at crate3 depot)
	(crate-at crate4 depot)
	(crate-at crate5 depot)
	(crate-at crate6 depot)
	(crate-at crate7 depot)
	(crate-at crate8 depot)
	(crate-at crate9 depot)
	(crate-at crate10 depot)
	(crate-at crate11 depot)
	(crate-at crate12 depot)
	(crate-at crate13 depot)
	(crate-at crate14 depot)
	(crate-at crate15 depot)
	(crate-at crate16 depot)
	(crate-at crate17 depot)
	(crate-at crate18 depot)
	(carrier-at carrier1 depot)
	(empty-space carrier1 space1)
	(empty-space carrier1 space2)
	(empty-space carrier1 space3)
	(empty-space carrier1 space4)
	(content-crate food crate1)
	(content-crate food crate2)
	(content-crate food crate3)
	(content-crate food crate4)
	(content-crate food crate5)
	(content-crate food crate6)
	(content-crate food crate7)
	(content-crate medicine crate8)
	(content-crate medicine crate9)
	(content-crate medicine crate10)
	(content-crate medicine crate11)
	(content-crate medicine crate12)
	(content-crate medicine crate13)
	(content-crate medicine crate14)
	(content-crate medicine crate15)
	(content-crate medicine crate16)
	(content-crate medicine crate17)
	(content-crate medicine crate18)
	(person-at person1 loc11)
	(person-at person2 loc2)
	(person-at person3 loc7)
	(person-at person4 loc11)
	(person-at person5 loc18)
	(person-at person6 loc18)
	(person-at person7 loc9)
	(person-at person8 loc6)
	(person-at person9 loc14)
	(person-at person10 loc1)
	(person-at person11 loc17)
	(person-at person12 loc14)
	(person-at person13 loc14)
	(person-at person14 loc9)
	(person-at person15 loc9)
	(person-at person16 loc8)
	(person-at person17 loc13)
	(person-at person18 loc18)
)
(:goal (and
	(drone-at drone1 depot)
	(has-content-person person1 food)
	(has-content-person person1 medicine)
	(has-content-person person2 food)
	(has-content-person person2 medicine)
	(has-content-person person3 food)
	(has-content-person person3 medicine)
	(has-content-person person4 medicine)
	(has-content-person person5 medicine)
	(has-content-person person6 medicine)
	(has-content-person person9 food)
	(has-content-person person9 medicine)
	(has-content-person person13 food)
	(has-content-person person13 medicine)
	(has-content-person person14 medicine)
	(has-content-person person16 food)
	(has-content-person person17 food)
	(has-content-person person17 medicine)
	(has-content-person person18 medicine)
))
)
