(define (problem drone_problem_d1_r1_l48_p48_c48_g48_ct2)
(:domain p2)
(:objects
	drone1 - drone
	depot - location
	loc1 - location
	loc2 - location
	loc3 - location
	loc4 - location
	loc5 - location
	loc6 - location
	loc7 - location
	loc8 - location
	loc9 - location
	loc10 - location
	loc11 - location
	loc12 - location
	loc13 - location
	loc14 - location
	loc15 - location
	loc16 - location
	loc17 - location
	loc18 - location
	loc19 - location
	loc20 - location
	loc21 - location
	loc22 - location
	loc23 - location
	loc24 - location
	loc25 - location
	loc26 - location
	loc27 - location
	loc28 - location
	loc29 - location
	loc30 - location
	loc31 - location
	loc32 - location
	loc33 - location
	loc34 - location
	loc35 - location
	loc36 - location
	loc37 - location
	loc38 - location
	loc39 - location
	loc40 - location
	loc41 - location
	loc42 - location
	loc43 - location
	loc44 - location
	loc45 - location
	loc46 - location
	loc47 - location
	loc48 - location
	crate1 - crate
	crate2 - crate
	crate3 - crate
	crate4 - crate
	crate5 - crate
	crate6 - crate
	crate7 - crate
	crate8 - crate
	crate9 - crate
	crate10 - crate
	crate11 - crate
	crate12 - crate
	crate13 - crate
	crate14 - crate
	crate15 - crate
	crate16 - crate
	crate17 - crate
	crate18 - crate
	crate19 - crate
	crate20 - crate
	crate21 - crate
	crate22 - crate
	crate23 - crate
	crate24 - crate
	crate25 - crate
	crate26 - crate
	crate27 - crate
	crate28 - crate
	crate29 - crate
	crate30 - crate
	crate31 - crate
	crate32 - crate
	crate33 - crate
	crate34 - crate
	crate35 - crate
	crate36 - crate
	crate37 - crate
	crate38 - crate
	crate39 - crate
	crate40 - crate
	crate41 - crate
	crate42 - crate
	crate43 - crate
	crate44 - crate
	crate45 - crate
	crate46 - crate
	crate47 - crate
	crate48 - crate
	food - content
	medicine - content
	person1 - person
	person2 - person
	person3 - person
	person4 - person
	person5 - person
	person6 - person
	person7 - person
	person8 - person
	person9 - person
	person10 - person
	person11 - person
	person12 - person
	person13 - person
	person14 - person
	person15 - person
	person16 - person
	person17 - person
	person18 - person
	person19 - person
	person20 - person
	person21 - person
	person22 - person
	person23 - person
	person24 - person
	person25 - person
	person26 - person
	person27 - person
	person28 - person
	person29 - person
	person30 - person
	person31 - person
	person32 - person
	person33 - person
	person34 - person
	person35 - person
	person36 - person
	person37 - person
	person38 - person
	person39 - person
	person40 - person
	person41 - person
	person42 - person
	person43 - person
	person44 - person
	person45 - person
	person46 - person
	person47 - person
	person48 - person
	carrier1 - carrier
	N0 - num
	N1 - num
	N2 - num
	N3 - num
	N4 - num
	N5 - num
	N6 - num
	N7 - num
)
(:init
	(drone-at drone1 depot)
	(crate-at crate1 depot)
	(crate-at crate2 depot)
	(crate-at crate3 depot)
	(crate-at crate4 depot)
	(crate-at crate5 depot)
	(crate-at crate6 depot)
	(crate-at crate7 depot)
	(crate-at crate8 depot)
	(crate-at crate9 depot)
	(crate-at crate10 depot)
	(crate-at crate11 depot)
	(crate-at crate12 depot)
	(crate-at crate13 depot)
	(crate-at crate14 depot)
	(crate-at crate15 depot)
	(crate-at crate16 depot)
	(crate-at crate17 depot)
	(crate-at crate18 depot)
	(crate-at crate19 depot)
	(crate-at crate20 depot)
	(crate-at crate21 depot)
	(crate-at crate22 depot)
	(crate-at crate23 depot)
	(crate-at crate24 depot)
	(crate-at crate25 depot)
	(crate-at crate26 depot)
	(crate-at crate27 depot)
	(crate-at crate28 depot)
	(crate-at crate29 depot)
	(crate-at crate30 depot)
	(crate-at crate31 depot)
	(crate-at crate32 depot)
	(crate-at crate33 depot)
	(crate-at crate34 depot)
	(crate-at crate35 depot)
	(crate-at crate36 depot)
	(crate-at crate37 depot)
	(crate-at crate38 depot)
	(crate-at crate39 depot)
	(crate-at crate40 depot)
	(crate-at crate41 depot)
	(crate-at crate42 depot)
	(crate-at crate43 depot)
	(crate-at crate44 depot)
	(crate-at crate45 depot)
	(crate-at crate46 depot)
	(crate-at crate47 depot)
	(crate-at crate48 depot)
	(carrier-at carrier1 depot)
	(carrier-capacity carrier1 N4)
	(crates-in-carrier carrier1 N0)
	(content-crate food crate1)
	(content-crate food crate2)
	(content-crate food crate3)
	(content-crate food crate4)
	(content-crate food crate5)
	(content-crate food crate6)
	(content-crate food crate7)
	(content-crate food crate8)
	(content-crate food crate9)
	(content-crate food crate10)
	(content-crate food crate11)
	(content-crate food crate12)
	(content-crate food crate13)
	(content-crate food crate14)
	(content-crate food crate15)
	(content-crate food crate16)
	(content-crate food crate17)
	(content-crate food crate18)
	(content-crate food crate19)
	(content-crate food crate20)
	(content-crate food crate21)
	(content-crate food crate22)
	(content-crate food crate23)
	(content-crate food crate24)
	(content-crate food crate25)
	(content-crate medicine crate26)
	(content-crate medicine crate27)
	(content-crate medicine crate28)
	(content-crate medicine crate29)
	(content-crate medicine crate30)
	(content-crate medicine crate31)
	(content-crate medicine crate32)
	(content-crate medicine crate33)
	(content-crate medicine crate34)
	(content-crate medicine crate35)
	(content-crate medicine crate36)
	(content-crate medicine crate37)
	(content-crate medicine crate38)
	(content-crate medicine crate39)
	(content-crate medicine crate40)
	(content-crate medicine crate41)
	(content-crate medicine crate42)
	(content-crate medicine crate43)
	(content-crate medicine crate44)
	(content-crate medicine crate45)
	(content-crate medicine crate46)
	(content-crate medicine crate47)
	(content-crate medicine crate48)
	(person-at person1 loc35)
	(person-at person2 loc18)
	(person-at person3 loc9)
	(person-at person4 loc16)
	(person-at person5 loc31)
	(person-at person6 loc23)
	(person-at person7 loc40)
	(person-at person8 loc19)
	(person-at person9 loc44)
	(person-at person10 loc23)
	(person-at person11 loc38)
	(person-at person12 loc41)
	(person-at person13 loc40)
	(person-at person14 loc9)
	(person-at person15 loc46)
	(person-at person16 loc20)
	(person-at person17 loc25)
	(person-at person18 loc48)
	(person-at person19 loc27)
	(person-at person20 loc42)
	(person-at person21 loc6)
	(person-at person22 loc1)
	(person-at person23 loc39)
	(person-at person24 loc13)
	(person-at person25 loc45)
	(person-at person26 loc22)
	(person-at person27 loc11)
	(person-at person28 loc16)
	(person-at person29 loc15)
	(person-at person30 loc41)
	(person-at person31 loc29)
	(person-at person32 loc25)
	(person-at person33 loc46)
	(person-at person34 loc44)
	(person-at person35 loc37)
	(person-at person36 loc27)
	(person-at person37 loc3)
	(person-at person38 loc26)
	(person-at person39 loc45)
	(person-at person40 loc37)
	(person-at person41 loc27)
	(person-at person42 loc43)
	(person-at person43 loc46)
	(person-at person44 loc3)
	(person-at person45 loc11)
	(person-at person46 loc29)
	(person-at person47 loc5)
	(person-at person48 loc17)
	(next-num N0 N1)
	(next-num N1 N2)
	(next-num N2 N3)
	(next-num N3 N4)
	(next-num N4 N5)
	(next-num N5 N6)
	(next-num N6 N7)
)
(:goal (and
	(drone-at drone1 depot)
	(has-content-person person1 medicine)
	(has-content-person person2 food)
	(has-content-person person2 medicine)
	(has-content-person person3 food)
	(has-content-person person4 food)
	(has-content-person person6 food)
	(has-content-person person6 medicine)
	(has-content-person person8 food)
	(has-content-person person8 medicine)
	(has-content-person person10 food)
	(has-content-person person11 medicine)
	(has-content-person person12 food)
	(has-content-person person13 food)
	(has-content-person person13 medicine)
	(has-content-person person14 medicine)
	(has-content-person person15 food)
	(has-content-person person17 food)
	(has-content-person person22 food)
	(has-content-person person22 medicine)
	(has-content-person person23 medicine)
	(has-content-person person24 food)
	(has-content-person person25 medicine)
	(has-content-person person26 food)
	(has-content-person person29 medicine)
	(has-content-person person30 food)
	(has-content-person person31 food)
	(has-content-person person32 medicine)
	(has-content-person person33 medicine)
	(has-content-person person34 food)
	(has-content-person person34 medicine)
	(has-content-person person35 medicine)
	(has-content-person person37 food)
	(has-content-person person37 medicine)
	(has-content-person person38 medicine)
	(has-content-person person39 food)
	(has-content-person person40 food)
	(has-content-person person40 medicine)
	(has-content-person person41 food)
	(has-content-person person42 medicine)
	(has-content-person person43 food)
	(has-content-person person43 medicine)
	(has-content-person person44 food)
	(has-content-person person44 medicine)
	(has-content-person person45 food)
	(has-content-person person45 medicine)
	(has-content-person person46 food)
	(has-content-person person46 medicine)
	(has-content-person person47 food)
))
)
